In [1]:
import pandas as pd

In [6]:
min_data = pd.read_csv('min_data.csv',index_col=0)
min_data

C:\Users\bitcamp\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

          REG_YYMM STD_CLSS_NM        신용카드
0           201901  건강보조식품 소매업  52,039,328
1           201901  건강보조식품 소매업  52,039,328
2           201901  건강보조식품 소매업  52,039,328
3           201901  건강보조식품 소매업  52,039,328
4           201901  건강보조식품 소매업  52,039,328
...            ...         ...         ...
24697787    202003    휴양콘도 운영업  47,855,261
24697788    202003    휴양콘도 운영업  47,855,261
24697789    202003    휴양콘도 운영업  47,855,261
24697790    202003    휴양콘도 운영업  47,855,261
24697791    202003    휴양콘도 운영업  47,855,261

[24697792 rows x 3 columns]

In [8]:
mapping = pd.read_csv('mapping.csv',index_col=0)
mapping

                 dacon_분류                        한국은행_분류
0                 한식 음식점업                           음식점업
1                 체인화 편의점                    기타 생활용품 소매업
2                    슈퍼마켓                    기타 생활용품 소매업
3             차량용 주유소 운영업                         연료 소매업
4                비알콜 음료점업                   주점 및 비알콜음료점업
5            기타 대형 종합 소매업                         종합 소매업
6                서양식 음식점업                           음식점업
7   피자 햄버거 샌드위치 및 유사 음식점업                           음식점업
8             빵 및 과자류 소매업                      음ㆍ식료품 소매업
9                 중식 음식점업                           음식점업
10          기타음식료품위주종합소매업                      음ㆍ식료품 소매업
11            기타 외국식 음식점업                           음식점업
12                일식 음식점업                           음식점업
13            과실 및 채소 소매업                      음ㆍ식료품 소매업
14     스포츠 및 레크레이션 용품 임대업                  개인 및 가정용품 임대업
15          화장품 및 방향제 소매업                    기타 생활용품 소매업
16                 택시 운송업                         육상 운송업
17           그외 기타 종합 소매업                         종합 소매업
18                    여관업               일반 및 생활 숙박시설 운영업
19            전시 및 행사 대행업        도서관, 사적지 및 유사 여가관련 서비스업
20                 육류 소매업                      음ㆍ식료품 소매업
21                    욕탕업               미용, 욕탕 및 유사 서비스업
22                수산물 소매업                      음ㆍ식료품 소매업
23                골프장 운영업                       스포츠 서비스업
24             차량용 가스 충전업                         연료 소매업
25                 버스 운송업                      육상 여객 운송업
26               일반유흥 주점업                   주점 및 비알콜음료점업
27                    호텔업               일반 및 생활 숙박시설 운영업
28                    면세점                   기타 상품 전문 소매업
29              정기 항공 운송업                      항공 여객 운송업
30               휴양콘도 운영업               일반 및 생활 숙박시설 운영업
31             건강보조식품 소매업                      음ㆍ식료품 소매업
32      관광 민예품 및 선물용품 소매업                   기타 상품 전문 소매업
33                 기타 주점업                   주점 및 비알콜음료점업
34              내항 여객 운송업                         해상 운송업
35                   여행사업             여행사 및 기타 여행보조 서비스업
36                자동차 임대업                          운송장비업
37                   마사지업               미용, 욕탕 및 유사 서비스업
38        그외 기타 스포츠시설 운영업                       스포츠 서비스업
39           기타 수상오락 서비스업                       스포츠 서비스업
40   그외 기타 분류안된 오락관련 서비스업                       스포츠 서비스업

In [9]:
mapping.columns=['STD_CLSS_NM','한국은행_분류']

In [10]:
mapping

              STD_CLSS_NM                        한국은행_분류
0                 한식 음식점업                           음식점업
1                 체인화 편의점                    기타 생활용품 소매업
2                    슈퍼마켓                    기타 생활용품 소매업
3             차량용 주유소 운영업                         연료 소매업
4                비알콜 음료점업                   주점 및 비알콜음료점업
5            기타 대형 종합 소매업                         종합 소매업
6                서양식 음식점업                           음식점업
7   피자 햄버거 샌드위치 및 유사 음식점업                           음식점업
8             빵 및 과자류 소매업                      음ㆍ식료품 소매업
9                 중식 음식점업                           음식점업
10          기타음식료품위주종합소매업                      음ㆍ식료품 소매업
11            기타 외국식 음식점업                           음식점업
12                일식 음식점업                           음식점업
13            과실 및 채소 소매업                      음ㆍ식료품 소매업
14     스포츠 및 레크레이션 용품 임대업                  개인 및 가정용품 임대업
15          화장품 및 방향제 소매업                    기타 생활용품 소매업
16                 택시 운송업                         육상 운송업
17           그외 기타 종합 소매업                         종합 소매업
18                    여관업               일반 및 생활 숙박시설 운영업
19            전시 및 행사 대행업        도서관, 사적지 및 유사 여가관련 서비스업
20                 육류 소매업                      음ㆍ식료품 소매업
21                    욕탕업               미용, 욕탕 및 유사 서비스업
22                수산물 소매업                      음ㆍ식료품 소매업
23                골프장 운영업                       스포츠 서비스업
24             차량용 가스 충전업                         연료 소매업
25                 버스 운송업                      육상 여객 운송업
26               일반유흥 주점업                   주점 및 비알콜음료점업
27                    호텔업               일반 및 생활 숙박시설 운영업
28                    면세점                   기타 상품 전문 소매업
29              정기 항공 운송업                      항공 여객 운송업
30               휴양콘도 운영업               일반 및 생활 숙박시설 운영업
31             건강보조식품 소매업                      음ㆍ식료품 소매업
32      관광 민예품 및 선물용품 소매업                   기타 상품 전문 소매업
33                 기타 주점업                   주점 및 비알콜음료점업
34              내항 여객 운송업                         해상 운송업
35                   여행사업             여행사 및 기타 여행보조 서비스업
36                자동차 임대업                          운송장비업
37                   마사지업               미용, 욕탕 및 유사 서비스업
38        그외 기타 스포츠시설 운영업                       스포츠 서비스업
39           기타 수상오락 서비스업                       스포츠 서비스업
40   그외 기타 분류안된 오락관련 서비스업                       스포츠 서비스업

In [12]:
min_data=pd.merge(min_data,mapping,how='left',on=['STD_CLSS_NM'])

In [13]:
min_data

          REG_YYMM STD_CLSS_NM        신용카드                 한국은행_분류
0           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업
1           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업
2           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업
3           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업
4           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업
...            ...         ...         ...                     ...
24697787    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업
24697788    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업
24697789    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업
24697790    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업
24697791    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업

[24697792 rows x 4 columns]

In [14]:
서비스업_생산지수 = pd.read_csv('서비스업_생산지수.csv',index_col=0)
서비스업_생산지수

,총지수,"수도, 하수 및 폐기물 처리, 원료 재생업",수도업,수도업,"하수, 폐수 및 분뇨 처리업","하수, 폐수 및 분뇨 처리업","폐기물 수집운반, 처리 및 원료재생업",도매 및 소매업,자동차 및 부품판매업,자동차 판매업,...,유원지 및 기타 오락관련 서비스업,"협회 및 단체, 수리 및 기타개인서비스업",협회 및 단체,산업 및 전문가 단체,개인 및 소비용품 수리업,자동차 수리업,개인 및 가정용품 수리업,기타 개인 서비스업,"미용, 욕탕 및 유사 서비스업",그외 기타 개인 서비스업
201901,108.6,105.9,106.1,106.1,95.6,95.6,109.0,106.7,110.8,107.9,...,101.6,100.8,104.4,104.4,106.2,107.3,102.8,95.6,91.6,101.1
201902,106.7,101.0,102.6,102.6,95.1,95.1,102.1,102.6,103.7,104.1,...,102.9,98.3,100.0,100.0,103.2,104.9,97.9,93.8,89.0,100.6
201903,107.4,104.8,105.6,105.6,96.5,96.5,106.9,104.8,107.7,107.4,...,101.4,100.4,101.4,101.4,104.8,106.8,98.3,96.5,91.0,104.2
201904,108.0,105.3,105.2,105.2,95.2,95.2,108.5,104.1,108.5,109.4,...,100.8,100.5,103.5,103.5,106.4,108.0,101.2,95.0,89.7,102.4
201905,108.4,107.1,107.5,107.5,96.2,96.2,110.3,105.0,108.4,109.6,...,99.3,99.7,105.1,105.1,106.4,108.5,99.4,93.1,87.1,101.4
201906,107.2,100.0,105.1,105.1,97.4,97.4,98.5,104.1,106.2,104.9,...,97.9,99.1,103.6,103.6,103.4,105.0,98.0,94.8,87.8,104.7
201907,108.4,108.3,105.7,105.7,97.4,97.4,113.0,104.3,110.2,110.4,...,97.6,98.0,103.3,103.3,102.8,105.5,93.9,93.1,86.4,102.6
201908,109.3,109.6,105.8,105.8,99.4,99.4,114.5,106.2,111.6,114.0,...,100.5,99.4,105.4,105.4,104.9,108.2,94.0,93.8,87.8,102.1
201909,108.2,104.5,105.1,105.1,100.0,100.0,105.7,104.1,112.4,115.4,...,97.8,98.0,97.9,97.9,103.9,107.0,93.4,93.0,85.6,103.5
201910,108.7,109.7,105.9,105.9,98.4,98.4,115.1,103.4,113.2,116.4,...,100.9,98.9,103.9,103.9,105.5,109.6,91.9,92.5,87.0,100.3
201911,109.6,108.1,106.0,106.0,97.8,97.8,112.3,105.3,113.6,117.6,...,107.4,100.2,104.9,104.9,106.0,110.3,91.7,94.5,88.6,102.8
201912,109.8,108.4,105.8,105.8,96.3,96.3,113.4,105.2,120.3,126.4,...,103.9,100.5,111.1,111.1,105.0,108.2,94.6,94.9,89.5,102.5
202001,110.3,105.2,104.3,104.3,101.0,101.0,106.9,104.2,105.2,105.3,...,112.7,99.7,107.3,107.3,104.0,107.4,92.9,94.7,87.7,104.5
202002,106.4,119.3,105.2,105.2,105.7,105.7,130.2,100.5,97.0,85.6,...,75.6,93.1,95.5,95.5,106.8,112.2,89.4,81.2,71.4,95.1
202003,101.7,110.1,104.8,104.8,97.5,97.5,116.6,97.2,114.3,120.5,...,33.2,78.7,94.7,94.7,95.7,99.8,82.1,61.6,57.8,66.9
202004,102.2,105.7,103.8,103.8,92.7,92.7,110.7,97.3,116.2,126.8,...,29.8,86.3,97.5,97.5,102.7,107.6,86.3,70.5,70.4,70.7
202005,104.6,107.4,104.4,104.4,97.8,97.8,111.8,100.9,122.8,139.7,...,41.2,94.5,90.4,90.4,106.9,111.5,91.7,84.9,80.4,91.3

In [15]:
a = min_data['REG_YYMM']
b = min_data['한국은행_분류']

In [17]:
data = []
for i,j in zip(a,b) :
    ddd = 서비스업_생산지수.loc[i,j]
    data.append(ddd)

In [18]:
min_data['서비스업_생산지수']=data

In [19]:
min_data

          REG_YYMM STD_CLSS_NM        신용카드                 한국은행_분류  서비스업_생산지수
0           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업       86.7
1           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업       86.7
2           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업       86.7
3           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업       86.7
4           201901  건강보조식품 소매업  52,039,328               음ㆍ식료품 소매업       86.7
...            ...         ...         ...                     ...        ...
24697787    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업       41.8
24697788    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업       41.8
24697789    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업       41.8
24697790    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업       41.8
24697791    202003    휴양콘도 운영업  47,855,261        일반 및 생활 숙박시설 운영업       41.8

[24697792 rows x 5 columns]

In [20]:
min_data.to_csv('min_data.csv')