In [152]:
import pandas as pd

In [163]:
dataset = pd.read_csv('dataset_min.csv',index_col=0)
submission = pd.read_csv('submission_min.csv',index_col=0)

In [164]:
last_mar=dataset[dataset['사용년']==0][dataset['사용월']==3]

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [165]:
last_may=dataset[dataset['사용년']==0][dataset['사용월']==5]

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [166]:
last_april=dataset[dataset['사용년']==0][dataset['사용월']==4]

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [167]:
this_mar=dataset[dataset['사용년']==1][dataset['사용월']==3]

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [168]:
print(len(last_mar))
print(len(this_mar))

630
609

In [169]:
mar_gap = pd.merge(last_mar,this_mar,on=['사용월','사용지역_도1','업종명_대분류1','업종명1'])

In [170]:
mar_gap

     사용년_x  사용월  사용지역_도1  업종명_대분류1  업종명1        이용금액_x  사용년_y        이용금액_y
0        0    3        0         0     0  215161897702      1  147494192925
1        0    3        0         0     6   46294820641      1   33691383982
2        0    3        0         0     7   20570214952      1   18715095314
3        0    3        0         0     9   20476576751      1   13327780001
4        0    3        0         0    11   11259256477      1    7348439049
..     ...  ...      ...       ...   ...           ...    ...           ...
600      0    3       16        11    21      37542532      1      19025100
601      0    3       16        12    26      21802000      1      12071000
602      0    3       16        12    33       7038000      1       2925000
603      0    3       16        13    24      45906137      1      36974064
604      0    3       16        17    37       5427000      1       1371000

[605 rows x 8 columns]

In [171]:
mar_gap['gap'] =  (mar_gap['이용금액_y']/mar_gap['이용금액_x'])*3/5

In [172]:
mar_gap

,사용년_x,사용월,사용지역_도1,업종명_대분류1,업종명1,이용금액_x,사용년_y,이용금액_y,gap
0,0,3,0,0,0,215161897702,1,147494192925,0.411302
1,0,3,0,0,6,46294820641,1,33691383982,0.436654
2,0,3,0,0,7,20570214952,1,18715095314,0.545889
3,0,3,0,0,9,20476576751,1,13327780001,0.390528
4,0,3,0,0,11,11259256477,1,7348439049,0.391595
...,...,...,...,...,...,...,...,...,...
600,0,3,16,11,21,37542532,1,19025100,0.304057
601,0,3,16,12,26,21802000,1,12071000,0.332199
602,0,3,16,12,33,7038000,1,2925000,0.249361
603,0,3,16,13,24,45906137,1,36974064,0.483256
604,0,3,16,17,37,5427000,1,1371000,0.151575

In [173]:
mar_gap_1 = mar_gap[[
 '사용지역_도1',
 '업종명_대분류1',
 '업종명1',
 '이용금액_y',
 'gap']]

In [174]:
mar_gap_1.columns = [
 '사용지역_도1',
 '업종명_대분류1',
 '업종명1',
 'this_mar',
 'last_year_gap']
mar_gap_1

     사용지역_도1  업종명_대분류1  업종명1      this_mar  last_year_gap
0          0         0     0  147494192925       0.411302
1          0         0     6   33691383982       0.436654
2          0         0     7   18715095314       0.545889
3          0         0     9   13327780001       0.390528
4          0         0    11    7348439049       0.391595
..       ...       ...   ...           ...            ...
600       16        11    21      19025100       0.304057
601       16        12    26      12071000       0.332199
602       16        12    33       2925000       0.249361
603       16        13    24      36974064       0.483256
604       16        17    37       1371000       0.151575

[605 rows x 5 columns]

In [175]:
submission

      사용년  사용월  사용지역_도1  업종명_대분류1  업종명1  이용금액
0       1    4        4         1    31     0
1       1    4        4         3    23     0
2       1    4        4         1    13     0
3       1    4        4         1    32     0
4       1    4        4        18    40     0
...   ...  ...      ...       ...   ...   ...
1389    1    7        8         0     7     0
1390    1    7        8         0     0     0
1391    1    7        8        14    27     0
1392    1    7        8         1    15     0
1393    1    7        8         3    30     0

[1394 rows x 6 columns]

In [176]:
submission_1 = pd.merge(submission,mar_gap_1,how='left',on=['사용지역_도1','업종명_대분류1','업종명1'])
submission_1

      사용년  사용월  사용지역_도1  업종명_대분류1  업종명1  이용금액      this_mar  last_year_gap
0       1    4        4         1    31     0  9.605901e+07       0.526644
1       1    4        4         3    23     0  2.915798e+09       0.633755
2       1    4        4         1    13     0  9.948169e+08       0.635512
3       1    4        4         1    32     0  1.331730e+07       0.319319
4       1    4        4        18    40     0           NaN            NaN
...   ...  ...      ...       ...   ...   ...           ...            ...
1389    1    7        8         0     7     0  1.315245e+09       0.547588
1390    1    7        8         0     0     0  1.615248e+10       0.422241
1391    1    7        8        14    27     0  1.524855e+07       0.253931
1392    1    7        8         1    15     0  4.288814e+08       0.352830
1393    1    7        8         3    30     0  1.273349e+07       0.071116

[1394 rows x 8 columns]

In [177]:
submission_2 = pd.merge(submission_1,last_april,how='left',on=['사용지역_도1','업종명_대분류1','업종명1'])
submission_2

,사용년_x,사용월_x,사용지역_도1,업종명_대분류1,업종명1,이용금액_x,this_mar,last_year_gap,사용년_y,사용월_y,이용금액_y
0,1,4,4,1,31,0,9.605901e+07,0.526644,0.0,4.0,1.065485e+08
1,1,4,4,3,23,0,2.915798e+09,0.633755,0.0,4.0,3.964893e+09
2,1,4,4,1,13,0,9.948169e+08,0.635512,0.0,4.0,8.276834e+08
3,1,4,4,1,32,0,1.331730e+07,0.319319,0.0,4.0,1.790561e+07
4,1,4,4,18,40,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1389,1,7,8,0,7,0,1.315245e+09,0.547588,0.0,4.0,1.428269e+09
1390,1,7,8,0,0,0,1.615248e+10,0.422241,0.0,4.0,2.216287e+10
1391,1,7,8,14,27,0,1.524855e+07,0.253931,0.0,4.0,4.051093e+07
1392,1,7,8,1,15,0,4.288814e+08,0.352830,0.0,4.0,6.872543e+08
1393,1,7,8,3,30,0,1.273349e+07,0.071116,0.0,4.0,1.019304e+08

In [178]:
last_mar

      사용년  사용월  사용지역_도1  업종명_대분류1  업종명1          이용금액
1258    0    3        0         0     0  215161897702
1259    0    3        0         0     6   46294820641
1260    0    3        0         0     7   20570214952
1261    0    3        0         0     9   20476576751
1262    0    3        0         0    11   11259256477
...   ...  ...      ...       ...   ...           ...
1883    0    3       16        11    21      37542532
1884    0    3       16        12    26      21802000
1885    0    3       16        12    33       7038000
1886    0    3       16        13    24      45906137
1887    0    3       16        17    37       5427000

[630 rows x 6 columns]

In [179]:
submission_2 = pd.merge(submission_1,last_april,how='left',on=['사용지역_도1','업종명_대분류1','업종명1'])
submission_2

,사용년_x,사용월_x,사용지역_도1,업종명_대분류1,업종명1,이용금액_x,this_mar,last_year_gap,사용년_y,사용월_y,이용금액_y
0,1,4,4,1,31,0,9.605901e+07,0.526644,0.0,4.0,1.065485e+08
1,1,4,4,3,23,0,2.915798e+09,0.633755,0.0,4.0,3.964893e+09
2,1,4,4,1,13,0,9.948169e+08,0.635512,0.0,4.0,8.276834e+08
3,1,4,4,1,32,0,1.331730e+07,0.319319,0.0,4.0,1.790561e+07
4,1,4,4,18,40,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1389,1,7,8,0,7,0,1.315245e+09,0.547588,0.0,4.0,1.428269e+09
1390,1,7,8,0,0,0,1.615248e+10,0.422241,0.0,4.0,2.216287e+10
1391,1,7,8,14,27,0,1.524855e+07,0.253931,0.0,4.0,4.051093e+07
1392,1,7,8,1,15,0,4.288814e+08,0.352830,0.0,4.0,6.872543e+08
1393,1,7,8,3,30,0,1.273349e+07,0.071116,0.0,4.0,1.019304e+08

In [180]:
submission_2['이용금액_x'] = submission_2['이용금액_y']*submission_2['last_year_gap']

In [181]:
submission_2['이용금액_x'].isnull().sum()

188

In [182]:
submission_3 = pd.merge(submission_2,last_mar,how='left',on=['사용지역_도1','업종명_대분류1','업종명1'])
submission_3

,사용년_x,사용월_x,사용지역_도1,업종명_대분류1,업종명1,이용금액_x,this_mar,last_year_gap,사용년_y,사용월_y,이용금액_y,사용년,사용월,이용금액
0,1,4,4,1,31,5.611312e+07,9.605901e+07,0.526644,0.0,4.0,1.065485e+08,0.0,3.0,1.094390e+08
1,1,4,4,3,23,2.512771e+09,2.915798e+09,0.633755,0.0,4.0,3.964893e+09,0.0,3.0,2.760497e+09
2,1,4,4,1,13,5.260023e+08,9.948169e+08,0.635512,0.0,4.0,8.276834e+08,0.0,3.0,9.392280e+08
3,1,4,4,1,32,5.717601e+06,1.331730e+07,0.319319,0.0,4.0,1.790561e+07,0.0,3.0,2.502319e+07
4,1,4,4,18,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1389,1,7,8,0,7,7.821036e+08,1.315245e+09,0.547588,0.0,4.0,1.428269e+09,0.0,3.0,1.441132e+09
1390,1,7,8,0,0,9.358084e+09,1.615248e+10,0.422241,0.0,4.0,2.216287e+10,0.0,3.0,2.295248e+10
1391,1,7,8,14,27,1.028697e+07,1.524855e+07,0.253931,0.0,4.0,4.051093e+07,0.0,3.0,3.603001e+07
1392,1,7,8,1,15,2.424839e+08,4.288814e+08,0.352830,0.0,4.0,6.872543e+08,0.0,3.0,7.293284e+08
1393,1,7,8,3,30,7.248878e+06,1.273349e+07,0.071116,0.0,4.0,1.019304e+08,0.0,3.0,1.074314e+08

In [183]:
submission_4 = submission_3.iloc[:,:6]

In [184]:
submission_4[submission_4['업종명1']==40][submission_4['이용금액_x'].notnull()]['이용금액_x'].mean()

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

400156.1964477989

In [101]:
submission_4[:50]

    사용년_x  사용월_x  사용지역_도1  업종명_대분류1  업종명1        이용금액_x
0       1      4        4         1    31  9.352186e+07
1       1      4        4         3    23  4.187951e+09
2       1      4        4         1    13  8.766705e+08
3       1      4        4         1    32  9.529336e+06
4       1      4        4        18    40           NaN
5       1      4        4         3    38  1.796936e+06
6       1      4        4         1    17  5.034736e+08
7       1      4        4         1     5  5.919117e+09
8       1      4        4        18    39  1.538236e+05
9       1      4        4         0    11  8.406421e+08
10      1      4        4        12    33  2.356987e+08
11      1      4        4         7    10  8.807792e+09
12      1      4        4         6    34  7.121942e+05
13      1      4        4        17    37  1.281740e+07
14      1      4        4        15    28           NaN
15      1      4        4         6    25           NaN
16      1      4        4         5     4  8.726284e+08
17      1      4        4         1     8  1.069176e+09
18      1      4        4         0     6  1.584470e+09
19      1      4        4         1    22  4.556124e+08
20      1      4        4         4     2  1.075316e+10
21      1      4        4         8    14  2.174503e+09
22      1      4        4         9    18  2.752787e+08
23      1      4        4        16    35  4.942502e+07
24      1      4        4        11    21  1.309362e+08
25      1      4        4         1    20  1.825448e+09
26      1      4        4        12    26  8.828028e+08
27      1      4        4         0    12  9.819465e+08
28      1      4        4         8    36  1.526129e+07
29      1      4        4        10    19  2.357858e+07
30      1      4        4         6    29           NaN
31      1      4        4         0     9  1.193565e+09
32      1      4        4        13    24  4.726198e+08
33      1      4        4         3     3  1.540530e+10
34      1      4        4         2     1  8.041833e+09
35      1      4        4         6    16           NaN
36      1      4        4         0     7  1.262329e+09
37      1      4        4         0     0  1.632682e+10
38      1      4        4        14    27  2.055509e+08
39      1      4        4         1    15  4.367791e+08
40      1      4        4         3    30  4.175758e+08
41      1      4        1         1    31  1.225681e+09
42      1      4        1         3    23  1.817488e+10
43      1      4        1         1    13  8.174617e+09
44      1      4        1         1    32  1.185625e+08
45      1      4        1        18    40           NaN
46      1      4        1         3    38  4.005976e+06
47      1      4        1         1    17  9.432029e+09
48      1      4        1         1     5  1.288348e+11
49      1      4        1        18    39  4.505907e+07

In [148]:
submission_4[submission_4['이용금액_x'].isnull()]

      사용년_x  사용월_x  사용지역_도1  업종명_대분류1  업종명1  이용금액_x
4         1      4        4        18    40     NaN
14        1      4        4        15    28     NaN
15        1      4        4         6    25     NaN
30        1      4        4         6    29     NaN
35        1      4        4         6    16     NaN
...     ...    ...      ...       ...   ...     ...
1367      1      7        8        15    28     NaN
1368      1      7        8         6    25     NaN
1376      1      7        8        16    35     NaN
1381      1      7        8         8    36     NaN
1383      1      7        8         6    29     NaN

[188 rows x 6 columns]

In [88]:
submission_4[submission_4['이용금액_x'].isnull()].iloc[i,5]=0

C:\Users\bitcamp\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [118]:
submission_4.loc[4,'업종명1']

40

In [119]:
submission_4[submission_4['업종명1']==submission_4.loc[4,'업종명1']][submission_4['이용금액_x'].notnull()]['이용금액_x'].mean()

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

666926.9940796648

In [108]:
submission_4[submission_4['이용금액_x'].isnull()]

      사용년_x  사용월_x  사용지역_도1  업종명_대분류1  업종명1  이용금액_x
4         1      4        4        18    40     NaN
14        1      4        4        15    28     NaN
15        1      4        4         6    25     NaN
30        1      4        4         6    29     NaN
35        1      4        4         6    16     NaN
...     ...    ...      ...       ...   ...     ...
1367      1      7        8        15    28     NaN
1368      1      7        8         6    25     NaN
1376      1      7        8        16    35     NaN
1381      1      7        8         8    36     NaN
1383      1      7        8         6    29     NaN

[188 rows x 6 columns]

In [112]:
submission_4[submission_4['이용금액_x'].isnull()].index

4

In [110]:
submission_4.loc[4,'이용금액_x']

nan

In [116]:
submission_4[submission_4['업종명1']==40].loc[4,'이용금액_x'][submission_4['이용금액_x'].notnull()]['이용금액_x'].mean()

IndexError: invalid index to scalar variable.

In [114]:
submission_4[submission_4['업종명1']==submission_4[submission_4['이용금액_x'].isnull()].loc[4,'이용금액_x']][submission_4['이용금액_x'].notnull()]['이용금액_x'].mean()

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

nan

In [185]:
for i in submission_4[submission_4['이용금액_x'].isnull()].index :
    
    submission_4.loc[i,'이용금액_x'] = submission_4[submission_4['업종명1']==submission_4.loc[i,'업종명1']][submission_4['이용금액_x'].notnull()]['이용금액_x'].mean()

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

In [186]:
submission_4

      사용년_x  사용월_x  사용지역_도1  업종명_대분류1  업종명1        이용금액_x
0         1      4        4         1    31  5.611312e+07
1         1      4        4         3    23  2.512771e+09
2         1      4        4         1    13  5.260023e+08
3         1      4        4         1    32  5.717601e+06
4         1      4        4        18    40  4.001562e+05
...     ...    ...      ...       ...   ...           ...
1389      1      7        8         0     7  7.821036e+08
1390      1      7        8         0     0  9.358084e+09
1391      1      7        8        14    27  1.028697e+07
1392      1      7        8         1    15  2.424839e+08
1393      1      7        8         3    30  7.248878e+06

[1394 rows x 6 columns]

In [187]:
real_submission = pd.read_csv('submission1.csv')
real_submission['AMT'] = submission_4['이용금액_x']
real_submission.to_csv('submission_0702_3.csv', index=None, encoding='utf-8-sig')

In [96]:
submission_5 = submission_4.copy()

In [98]:
submission_5[submission_5['이용금액_x'].isnull()].iloc[i,5]=50

C:\Users\bitcamp\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [99]:
submission_5[submission_5['이용금액_x'].isnull()]

      사용년_x  사용월_x  사용지역_도1  업종명_대분류1  업종명1  이용금액_x
4         1      4        4        18    40     NaN
14        1      4        4        15    28     NaN
15        1      4        4         6    25     NaN
30        1      4        4         6    29     NaN
35        1      4        4         6    16     NaN
...     ...    ...      ...       ...   ...     ...
1367      1      7        8        15    28     NaN
1368      1      7        8         6    25     NaN
1376      1      7        8        16    35     NaN
1381      1      7        8         8    36     NaN
1383      1      7        8         6    29     NaN

[188 rows x 6 columns]

In [93]:
submission_4[submission_4['이용금액_x'].isnull()].iloc[0,4]

40

In [90]:
submission_4[submission_4['이용금액_x'].isnull()].iloc[1,5] =

SyntaxError: invalid syntax (<ipython-input-90-39f1c5805e46>, line 1)

In [44]:
submission_3[submission_3['이용금액_x']==None]

Empty DataFrame
Columns: [사용년_x, 사용월_x, 사용지역_도1, 업종명_대분류1, 업종명1, 이용금액_x, this_mar, last_year_gap, 사용년_y, 사용월_y, 이용금액_y, 사용년, 사용월, 이용금액, 이용금액_may]
Index: []

In [27]:
submission_3['이용금액_may'] = submission_3['이용금액']*submission_3['last_year_gap']

In [33]:
submission_3[['이용금액_x','이용금액_may']][-50:]

            이용금액_x      이용금액_may
1344  7.817858e+08  8.628667e+08
1345  2.863804e+10  2.924342e+10
1346  1.303756e+10  1.292348e+10
1347           NaN           NaN
1348  1.940645e+09  1.961622e+09
1349  2.109348e+10  2.165835e+10
1350  4.215949e+06  8.423086e+06
1351  8.687518e+08  9.381569e+08
1352  4.679283e+07  4.077782e+07
1353  1.007790e+08  1.089949e+08
1354  3.347195e+09  2.520056e+09
1355  8.119712e+08  7.780146e+08
1356  1.633876e+07  2.203097e+07
1357           NaN           NaN
1358  1.493154e+06  1.542000e+06
1359  2.036828e+09  2.018012e+09
1360  7.340158e+09  7.340310e+09
1361  7.380777e+05  9.420000e+05
1362  8.622451e+08  8.979285e+08
1363  1.261215e+08  1.335603e+08
1364  3.653968e+09  3.568038e+09
1365           NaN           NaN
1366  4.886470e+06  5.711000e+06
1367           NaN           NaN
1368           NaN           NaN
1369  8.023135e+08  7.910442e+08
1370  1.273399e+09  1.349318e+09
1371  1.253301e+09  1.266957e+09
1372  2.412025e+08  2.669487e+08
1373  1.401735e+10  1.406051e+10
1374  1.712424e+09  1.701217e+09
1375  1.986787e+08  2.127699e+08
1376           NaN           NaN
1377  9.658112e+07  1.151358e+08
1378  2.615907e+09  2.608771e+09
1379  3.344435e+08  3.592442e+08
1380  5.288536e+08  5.970258e+08
1381           NaN           NaN
1382  3.850168e+06  4.375000e+06
1383           NaN           NaN
1384  1.196538e+09  1.286269e+09
1385  5.809076e+08  6.396585e+08
1386  2.062279e+10  2.037907e+10
1387  8.284172e+09  8.227830e+09
1388  4.298470e+05  9.933600e+05
1389  1.303506e+09  1.315245e+09
1390  1.559681e+10  1.615248e+10
1391  1.714496e+07  1.524855e+07
1392  4.041398e+08  4.288814e+08
1393  1.208146e+07  1.273349e+07

In [21]:
submission_2[:50]

,사용년_x,사용월_x,사용지역_도1,업종명_대분류1,업종명1,이용금액_x,this_mar,last_year_gap,사용년_y,사용월_y,이용금액_y
0,1,4,4,1,31,9.352186e+07,9.605901e+07,0.877740,0.0,4.0,1.065485e+08
1,1,4,4,3,23,4.187951e+09,2.915798e+09,1.056258,0.0,4.0,3.964893e+09
2,1,4,4,1,13,8.766705e+08,9.948169e+08,1.059186,0.0,4.0,8.276834e+08
3,1,4,4,1,32,9.529336e+06,1.331730e+07,0.532198,0.0,4.0,1.790561e+07
4,1,4,4,18,40,NaN,NaN,NaN,NaN,NaN,NaN
5,1,4,4,3,38,1.796936e+06,2.075000e+06,0.304354,0.0,4.0,5.904100e+06
6,1,4,4,1,17,5.034736e+08,4.702002e+08,1.160608,0.0,4.0,4.338018e+08
7,1,4,4,1,5,5.919117e+09,6.384111e+09,0.798850,0.0,4.0,7.409552e+09
8,1,4,4,18,39,1.538236e+05,2.610000e+05,0.102073,0.0,4.0,1.507000e+06
9,1,4,4,0,11,8.406421e+08,8.876362e+08,0.775417,0.0,4.0,1.084116e+09
10,1,4,4,12,33,2.356987e+08,2.507374e+08,0.796654,0.0,4.0,2.958609e+08
11,1,4,4,7,10,8.807792e+09,8.543165e+09,1.260685,0.0,4.0,6.986513e+09
12,1,4,4,6,34,7.121942e+05,4.580000e+05,0.281500,0.0,4.0,2.530000e+06
13,1,4,4,17,37,1.281740e+07,1.446100e+07,0.372946,0.0,4.0,3.436800e+07
14,1,4,4,15,28,NaN,NaN,NaN,0.0,4.0,1.137300e+05
15,1,4,4,6,25,NaN,NaN,NaN,0.0,4.0,9.400000e+05
16,1,4,4,5,4,8.726284e+08,9.029846e+08,0.774966,0.0,4.0,1.126022e+09
17,1,4,4,1,8,1.069176e+09,1.143258e+09,0.940462,0.0,4.0,1.136863e+09
18,1,4,4,0,6,1.584470e+09,1.728089e+09,0.789574,0.0,4.0,2.006742e+09
19,1,4,4,1,22,4.556124e+08,5.175731e+08,0.880368,0.0,4.0,5.175251e+08
20,1,4,4,4,2,1.075316e+10,1.069800e+10,1.146899,0.0,4.0,9.375852e+09
21,1,4,4,8,14,2.174503e+09,2.192115e+09,0.697374,0.0,4.0,3.118131e+09
22,1,4,4,9,18,2.752787e+08,3.484187e+08,0.524666,0.0,4.0,5.246744e+08
23,1,4,4,16,35,4.942502e+07,7.774515e+07,1.078963,0.0,4.0,4.580790e+07
24,1,4,4,11,21,1.309362e+08,1.501253e+08,0.582951,0.0,4.0,2.246092e+08
25,1,4,4,1,20,1.825448e+09,1.791210e+09,1.312417,0.0,4.0,1.390905e+09
26,1,4,4,12,26,8.828028e+08,9.667878e+08,0.680086,0.0,4.0,1.298075e+09
27,1,4,4,0,12,9.819465e+08,1.229889e+09,0.618209,0.0,4.0,1.588372e+09
28,1,4,4,8,36,1.526129e+07,4.607000e+06,4.924745,0.0,4.0,3.098900e+06
29,1,4,4,10,19,2.357858e+07,4.624906e+07,0.214460,0.0,4.0,1.099441e+08
30,1,4,4,6,29,NaN,NaN,NaN,NaN,NaN,NaN
31,1,4,4,0,9,1.193565e+09,1.317951e+09,0.891387,0.0,4.0,1.338998e+09
32,1,4,4,13,24,4.726198e+08,5.065994e+08,0.835616,0.0,4.0,5.655943e+08
33,1,4,4,3,3,1.540530e+10,1.495146e+10,0.915687,0.0,4.0,1.682376e+10
34,1,4,4,2,1,8.041833e+09,8.169183e+09,0.930878,0.0,4.0,8.638972e+09
35,1,4,4,6,16,NaN,NaN,NaN,0.0,4.0,7.141000e+04
36,1,4,4,0,7,1.262329e+09,1.275528e+09,0.865878,0.0,4.0,1.457860e+09
37,1,4,4,0,0,1.632682e+10,1.806329e+10,0.731152,0.0,4.0,2.233026e+10
38,1,4,4,14,27,2.055509e+08,3.675608e+08,0.659748,0.0,4.0,3.115597e+08
39,1,4,4,1,15,4.367791e+08,4.529247e+08,0.651382,0.0,4.0,6.705421e+08
40,1,4,4,3,30,4.175758e+08,5.598760e+08,0.412202,0.0,4.0,1.013036e+09
41,1,4,1,1,31,1.225681e+09,1.284597e+09,1.002718,0.0,4.0,1.222358e+09
42,1,4,1,3,23,1.817488e+10,1.428287e+10,0.961463,0.0,4.0,1.890336e+10
43,1,4,1,1,13,8.174617e+09,8.114936e+09,1.265767,0.0,4.0,6.458230e+09
44,1,4,1,1,32,1.185625e+08,8.849495e+07,0.709384,0.0,4.0,1.671345e+08
45,1,4,1,18,40,NaN,NaN,NaN,NaN,NaN,NaN
46,1,4,1,3,38,4.005976e+06,7.012700e+06,0.109245,0.0,4.0,3.666980e+07
47,1,4,1,1,17,9.432029e+09,9.593390e+09,1.119058,0.0,4.0,8.428541e+09
48,1,4,1,1,5,1.288348e+11,1.348339e+11,0.816577,0.0,4.0,1.577742e+11
49,1,4,1,18,39,4.505907e+07,4.613706e+07,0.631563,0.0,4.0,7.134534e+07

In [78]:
submission_2.fillna(submission_2.mean())

,사용년_x,사용월_x,사용지역_도1,업종명_대분류1,업종명1,이용금액_x,this_mar,last_year_gap,사용년_y,사용월_y,이용금액_y
0,1,4,4,1,31,9.316846e+07,9.605901e+07,-1.338001e+07,0.0,4.0,1.065485e+08
1,1,4,4,3,23,4.120194e+09,2.915798e+09,1.553009e+08,0.0,4.0,3.964893e+09
2,1,4,4,1,13,8.832724e+08,9.948169e+08,5.558899e+07,0.0,4.0,8.276834e+08
3,1,4,4,1,32,6.199720e+06,1.331730e+07,-1.170589e+07,0.0,4.0,1.790561e+07
4,1,4,4,18,40,5.537663e+09,5.682449e+09,-1.102627e+09,0.0,4.0,6.329697e+09
...,...,...,...,...,...,...,...,...,...,...,...
1389,1,7,8,0,7,1.302382e+09,1.315245e+09,-1.258865e+08,0.0,4.0,1.428269e+09
1390,1,7,8,0,0,1.536287e+10,1.615248e+10,-6.800000e+09,0.0,4.0,2.216287e+10
1391,1,7,8,14,27,1.972947e+07,1.524855e+07,-2.078146e+07,0.0,4.0,4.051093e+07
1392,1,7,8,1,15,3.868074e+08,4.288814e+08,-3.004470e+08,0.0,4.0,6.872543e+08
1393,1,7,8,3,30,7.232397e+06,1.273349e+07,-9.469795e+07,0.0,4.0,1.019304e+08

In [80]:
real_submission

        id  REG_YYMM CARD_SIDO_NM            STD_CLSS_NM           AMT
0        0    202004           강원             건강보조식품 소매업  9.316846e+07
1        1    202004           강원                골프장 운영업  4.120194e+09
2        2    202004           강원            과실 및 채소 소매업  8.832724e+08
3        3    202004           강원      관광 민예품 및 선물용품 소매업  6.199720e+06
4        4    202004           강원   그외 기타 분류안된 오락관련 서비스업           NaN
...    ...       ...          ...                    ...           ...
1389  1389    202007           충북  피자 햄버거 샌드위치 및 유사 음식점업  1.302382e+09
1390  1390    202007           충북                한식 음식점업  1.536287e+10
1391  1391    202007           충북                    호텔업  1.972947e+07
1392  1392    202007           충북          화장품 및 방향제 소매업  3.868074e+08
1393  1393    202007           충북               휴양콘도 운영업  7.232397e+06

[1394 rows x 5 columns]

In [79]:
real_submission = pd.read_csv('submission1.csv')
real_submission['AMT'] = submission_2['이용금액_x']
real_submission.to_csv('submission_0701_2.csv', index=None, encoding='utf-8-sig')

In [72]:
list(submission_2)

['사용년_x',
 '사용월_x',
 '사용지역_도1',
 '업종명_대분류1',
 '업종명1',
 '이용금액_x',
 'this_mar',
 'last_year_gap',
 '사용년_y',
 '사용월_y',
 '이용금액_y']

In [ ]:
submission_3 = submission_2[['사용년_x',
 '사용월_x',
 '사용지역_도1',
 '업종명_대분류1',
 '업종명1',
 '이용금액_x',
 'this_mar',
 'last_year_gap',
 '사용년_y',
 '사용월_y',
 '이용금액_y']]

In [9]:
this_mar[this_mar['사용지역_도1']==0][this_mar['업종명_대분류1']==1]

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      사용년  사용월  사용지역_도1  업종명_대분류1  업종명1         이용금액
8835    1    3        0         1     5  85944403598
8836    1    3        0         1     8  14350083255
8837    1    3        0         1    13   8005379734
8838    1    3        0         1    15  15531843111
8839    1    3        0         1    17  40433017255
8840    1    3        0         1    20  16014475439
8841    1    3        0         1    22   3342043120
8842    1    3        0         1    31   1178972099
8843    1    3        0         1    32     53586140

In [5]:
this_mar=dataset[dataset['사용년']==1][dataset['사용월']==3]
this_mar

C:\Users\bitcamp\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

      사용년  사용월  사용지역_도1  업종명_대분류1  업종명1          이용금액
8829    1    3        0         0     0  147494192925
8830    1    3        0         0     6   33691383982
8831    1    3        0         0     7   18715095314
8832    1    3        0         0     9   13327780001
8833    1    3        0         0    11    7348439049
...   ...  ...      ...       ...   ...           ...
9433    1    3       16        11    21      19025100
9434    1    3       16        12    26      12071000
9435    1    3       16        12    33       2925000
9436    1    3       16        13    24      36974064
9437    1    3       16        17    37       1371000

[609 rows x 6 columns]

In [68]:
x = this_mar.iloc[:,2:5]
y = this_mar.iloc[:,5]

In [70]:
y

8829    147494192925
8830     33691383982
8831     18715095314
8832     13327780001
8833      7348439049
            ...
9433        19025100
9434        12071000
9435         2925000
9436        36974064
9437         1371000
Name: 이용금액, Length: 609, dtype: int64

In [72]:
test = submission.iloc[:,2:5]

# 머신러닝

In [73]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_squared_log_error
from xgboost import XGBRegressor

In [74]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.pipeline import Pipeline , make_pipeline
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV, RandomizedSearchCV

In [78]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, random_state=66, test_size=0.2)

In [79]:
pipe = Pipeline([("scaler",RobustScaler()),('rf',RandomForestRegressor())])

In [80]:
parameters = [
    { 'rf__max_depth':[3,5,25,100, 200, 300],
     'rf__n_estimators':[10, 50, 150, 250, 300],
    'rf__max_leaf_nodes':[1000000,1005000,10000000]}
]

In [81]:
model = RandomizedSearchCV(pipe, parameters, cv=5)
model.fit(x_train, y_train)
pred = model.predict(x_test)
RMSLE = np.sqrt(mean_squared_log_error(y_test, pred))
MAE = mean_absolute_error(y_test, pred)
print('rmsle는',RMSLE)
print('mae는',MAE)

rmsle는 1.8252680311200438
mae는 3134233348.3034973

In [82]:
test_pred = model.predict(test)
real_submission = pd.read_csv('submission1.csv')
real_submission['AMT'] = test_pred
real_submission.to_csv('submission_0701_1.csv', index=None, encoding='utf-8-sig')

In [174]:
print("============================")
print("최적의 매개 변수는(estimator):", model.best_estimator_) # 전체 params 다 나옴
print("============================")
print("최적의 매개 변수는(params):", model.best_params_)
print("============================")

============================
최적의 매개 변수는(estimator): Pipeline(memory=None,
         steps=[('scaler',
                 RobustScaler(copy=True, quantile_range=(25.0, 75.0),
                              with_centering=True, with_scaling=True)),
                ('rf',
                 RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                       criterion='mse', max_depth=100,
                                       max_features='auto',
                                       max_leaf_nodes=1005000, max_samples=None,
                                       min_impurity_decrease=0.0,
                                       min_impurity_split=None,
                                       min_samples_leaf=1, min_samples_split=2,
                                       min_weight_fraction_leaf=0.0,
                                       n_estimators=300, n_jobs=None,
                                       oob_score=False, random_state=None,
                                       verbose=0, warm_start=False))],
         verbose=False)
============================
최적의 매개 변수는(params): {'rf__n_estimators': 300, 'rf__max_leaf_nodes': 1005000, 'rf__max_depth': 100}
============================

In [76]:
model = RandomForestRegressor(n_estimators=300)
model.fit(x_train, y_train)
pred = model.predict(x_test)
RMSLE = np.sqrt(mean_squared_log_error(y_test, pred))
RMSLE

1.8484167144181893

In [77]:
model = RandomForestRegressor(n_estimators=150)
model.fit(x_train, y_train)
pred = model.predict(x_test)
RMSLE = np.sqrt(mean_squared_log_error(y_test, pred))
MAE = mean_absolute_error(y_test, pred)
print('rmsle는',RMSLE)
print('mae는',MAE)

rmsle는 1.8522503186899872
mae는 3211696601.852732

In [120]:
model = XGBRegressor(n_estimators=150)
model.fit(x_train, y_train)
pred = model.predict(x_test)
RMSLE = np.sqrt(mean_squared_log_error(y_test, pred))
MAE = mean_absolute_error(y_test, pred)
print('rmsle는',RMSLE)
print('mae는',MAE)

ValueError: Mean Squared Logarithmic Error cannot be used when targets contain negative values.

In [91]:
test_pred = model.predict(test)
real_submission = pd.read_csv('submission1.csv')
real_submission['AMT'] = test_pred
real_submission.to_csv('submission_0630_2.csv', index=None, encoding='utf-8-sig')

In [102]:
submission_real

        id  REG_YYMM CARD_SIDO_NM            STD_CLSS_NM           AMT
0        0    202004           강원             건강보조식품 소매업  9.751899e+07
1        1    202004           강원                골프장 운영업  3.760515e+09
2        2    202004           강원            과실 및 채소 소매업  9.334674e+08
3        3    202004           강원      관광 민예품 및 선물용품 소매업  1.834808e+07
4        4    202004           강원   그외 기타 분류안된 오락관련 서비스업  1.619220e+06
...    ...       ...          ...                    ...           ...
1389  1389    202007           충북  피자 햄버거 샌드위치 및 유사 음식점업  1.462200e+09
1390  1390    202007           충북                한식 음식점업  2.084806e+10
1391  1391    202007           충북                    호텔업  1.708192e+07
1392  1392    202007           충북          화장품 및 방향제 소매업  4.778178e+08
1393  1393    202007           충북               휴양콘도 운영업  2.197401e+08

[1394 rows x 5 columns]

In [105]:
submission_real.to_csv('submission_0630_1.csv', index=None, encoding='utf-8-sig')

In [106]:
submission_real

        id  REG_YYMM CARD_SIDO_NM            STD_CLSS_NM           AMT
0        0    202004           강원             건강보조식품 소매업  9.751899e+07
1        1    202004           강원                골프장 운영업  3.760515e+09
2        2    202004           강원            과실 및 채소 소매업  9.334674e+08
3        3    202004           강원      관광 민예품 및 선물용품 소매업  1.834808e+07
4        4    202004           강원   그외 기타 분류안된 오락관련 서비스업  1.619220e+06
...    ...       ...          ...                    ...           ...
1389  1389    202007           충북  피자 햄버거 샌드위치 및 유사 음식점업  1.462200e+09
1390  1390    202007           충북                한식 음식점업  2.084806e+10
1391  1391    202007           충북                    호텔업  1.708192e+07
1392  1392    202007           충북          화장품 및 방향제 소매업  4.778178e+08
1393  1393    202007           충북               휴양콘도 운영업  2.197401e+08

[1394 rows x 5 columns]

In [62]:
submission_real = submission_real.reset_index()

In [107]:
submission_real.to_csv('submission_0630_1.csv', index=None, encoding='utf-8-sig')

In [ ]:
# xgb 완전 쓰레기...

In [40]:
x_train.shape

(7550, 5)

In [110]:
x_test.shape

(1888, 5)

In [85]:
from keras.models import Sequential, Model 
from keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense, LSTM

model = Sequential()
model.add(Dense(1600, input_shape=(3,), activation='elu'))
model.add(Dense(3600, activation='elu'))
model.add(Dropout(0.2))

model.add(Dense(1280, activation='elu'))
model.add(Dense(640, activation='elu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='elu'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 1600)              6400
_________________________________________________________________
dense_7 (Dense)              (None, 3600)              5763600
_________________________________________________________________
dropout_3 (Dropout)          (None, 3600)              0
_________________________________________________________________
dense_8 (Dense)              (None, 1280)              4609280
_________________________________________________________________
dense_9 (Dense)              (None, 640)               819840
_________________________________________________________________
dropout_4 (Dropout)          (None, 640)               0
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 641
=================================================================
Total params: 11,199,761
Trainable params: 11,199,761
Non-trainable params: 0
_________________________________________________________________

In [86]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=500, batch_size=100, validation_split=0.2)

Train on 389 samples, validate on 98 samples
Epoch 1/500
389/389 [==============================] - 1s 2ms/step - loss: 246692097290556473344.0000 - mse: 246692093491729661952.0000 - val_loss: 358196400006446972928.0000 - val_mse: 358196400006446972928.0000
Epoch 2/500
389/389 [==============================] - 0s 97us/step - loss: 246692102717451927552.0000 - mse: 246692093491729661952.0000 - val_loss: 358196400006446972928.0000 - val_mse: 358196400006446972928.0000
Epoch 3/500
389/389 [==============================] - 0s 95us/step - loss: 246692032846173143040.0000 - mse: 246692040715171528704.0000 - val_loss: 358196329637702795264.0000 - val_mse: 358196329637702795264.0000
Epoch 4/500
389/389 [==============================] - 0s 92us/step - loss: 246691894188994723840.0000 - mse: 246691882385497128960.0000 - val_loss: 358196118531470262272.0000 - val_mse: 358196118531470262272.0000
Epoch 5/500
389/389 [==============================] - 0s 96us/step - loss: 246691512599103209472.0000 - mse: 246691512949590196224.0000 - val_loss: 358195485212772663296.0000 - val_mse: 358195485212772663296.0000
Epoch 6/500
389/389 [==============================] - 0s 95us/step - loss: 246690657263852027904.0000 - mse: 246690650932474019840.0000 - val_loss: 358194253759749554176.0000 - val_mse: 358194253759749554176.0000
Epoch 7/500
389/389 [==============================] - 0s 98us/step - loss: 246689087172553605120.0000 - mse: 246689085227916066816.0000 - val_loss: 358191966775563780096.0000 - val_mse: 358191966775563780096.0000
Epoch 8/500
389/389 [==============================] - 0s 95us/step - loss: 246685992259309502464.0000 - mse: 246686006595358294016.0000 - val_loss: 358187744650913120256.0000 - val_mse: 358187744650913120256.0000
Epoch 9/500
389/389 [==============================] - 0s 87us/step - loss: 246680521044225556480.0000 - mse: 246680517833312436224.0000 - val_loss: 358180320748402376704.0000 - val_mse: 358180320748402376704.0000
Epoch 10/500
389/389 [==============================] - 0s 92us/step - loss: 246670390703735832576.0000 - mse: 246670402326336897024.0000 - val_loss: 358168076586915463168.0000 - val_mse: 358168076586915463168.0000
Epoch 11/500
389/389 [==============================] - 0s 95us/step - loss: 246654754009014206464.0000 - mse: 246654762872943411200.0000 - val_loss: 358148478891661983744.0000 - val_mse: 358148478891661983744.0000
Epoch 12/500
389/389 [==============================] - 0s 90us/step - loss: 246630741556934082560.0000 - mse: 246630749538992783360.0000 - val_loss: 358117798119200522240.0000 - val_mse: 358117798119200522240.0000
Epoch 13/500
389/389 [==============================] - 0s 92us/step - loss: 246594876075549687808.0000 - mse: 246594879071648219136.0000 - val_loss: 358071706591764152320.0000 - val_mse: 358071706591764152320.0000
Epoch 14/500
389/389 [==============================] - 0s 90us/step - loss: 246538493628048801792.0000 - mse: 246538513707561910272.0000 - val_loss: 358004258150469861376.0000 - val_mse: 358004258150469861376.0000
Epoch 15/500
389/389 [==============================] - 0s 92us/step - loss: 246454557283483418624.0000 - mse: 246454563795757957120.0000 - val_loss: 357908627027132416000.0000 - val_mse: 357908627027132416000.0000
Epoch 16/500
389/389 [==============================] - 0s 95us/step - loss: 246342987209960521728.0000 - mse: 246342994151864270848.0000 - val_loss: 357776509709938851840.0000 - val_mse: 357776509709938851840.0000
Epoch 17/500
389/389 [==============================] - 0s 95us/step - loss: 246184441160717271040.0000 - mse: 246184453371231993856.0000 - val_loss: 357598863815262339072.0000 - val_mse: 357598863815262339072.0000
Epoch 18/500
389/389 [==============================] - 0s 96us/step - loss: 245982206093259997184.0000 - mse: 245982213600465387520.0000 - val_loss: 357359786006918725632.0000 - val_mse: 357359786006918725632.0000
Epoch 19/500
389/389 [==============================] - 0s 92us/step - loss: 245700588570095878144.0000 - mse: 245700597886266376192.0000 - val_loss: 357049635766955671552.0000 - val_mse: 357049635766955671552.0000
Epoch 20/500
389/389 [==============================] - 0s 95us/step - loss: 245337021895803305984.0000 - mse: 245337002585100386304.0000 - val_loss: 356660179952304390144.0000 - val_mse: 356660179952304390144.0000
Epoch 21/500
389/389 [==============================] - 0s 95us/step - loss: 244910107387633467392.0000 - mse: 244910093006360543232.0000 - val_loss: 356182903944919384064.0000 - val_mse: 356182903944919384064.0000
Epoch 22/500
389/389 [==============================] - 0s 94us/step - loss: 244399269876016185344.0000 - mse: 244399268700188835840.0000 - val_loss: 355615204101266079744.0000 - val_mse: 355615204101266079744.0000
Epoch 23/500
389/389 [==============================] - 0s 94us/step - loss: 243743656858820640768.0000 - mse: 243743660702871584768.0000 - val_loss: 354977944753993154560.0000 - val_mse: 354977944753993154560.0000
Epoch 24/500
389/389 [==============================] - 0s 97us/step - loss: 243030266354121768960.0000 - mse: 243030262374398427136.0000 - val_loss: 354306239906445262848.0000 - val_mse: 354306239906445262848.0000
Epoch 25/500
389/389 [==============================] - 0s 91us/step - loss: 242351040123453800448.0000 - mse: 242351045663409569792.0000 - val_loss: 353643049676942868480.0000 - val_mse: 353643049676942868480.0000
Epoch 26/500
389/389 [==============================] - 0s 96us/step - loss: 241721894397530669056.0000 - mse: 241721931498275209216.0000 - val_loss: 353071514736731881472.0000 - val_mse: 353071514736731881472.0000
Epoch 27/500
389/389 [==============================] - 0s 95us/step - loss: 240989865780098990080.0000 - mse: 240989867860408926208.0000 - val_loss: 352665874110919737344.0000 - val_mse: 352665874110919737344.0000
Epoch 28/500
389/389 [==============================] - 0s 97us/step - loss: 240659397300146765824.0000 - mse: 240659381053378527232.0000 - val_loss: 352362444086025650176.0000 - val_mse: 352362444086025650176.0000
Epoch 29/500
389/389 [==============================] - 0s 92us/step - loss: 240385547529849503744.0000 - mse: 240385541085411147776.0000 - val_loss: 352117138643822313472.0000 - val_mse: 352117138643822313472.0000
Epoch 30/500
389/389 [==============================] - 0s 95us/step - loss: 240055234722654060544.0000 - mse: 240055212608055148544.0000 - val_loss: 351862966739852591104.0000 - val_mse: 351862966739852591104.0000
Epoch 31/500
389/389 [==============================] - 0s 97us/step - loss: 239912335837518233600.0000 - mse: 239912328873002401792.0000 - val_loss: 351552288734308204544.0000 - val_mse: 351552288734308204544.0000
Epoch 32/500
389/389 [==============================] - 0s 92us/step - loss: 239543128289823096832.0000 - mse: 239543121664488243200.0000 - val_loss: 351223314855277625344.0000 - val_mse: 351223314855277625344.0000
Epoch 33/500
389/389 [==============================] - 0s 97us/step - loss: 239274439824962158592.0000 - mse: 239274436207031877632.0000 - val_loss: 350876608052714274816.0000 - val_mse: 350876608052714274816.0000
Epoch 34/500
389/389 [==============================] - 0s 95us/step - loss: 239007098564281663488.0000 - mse: 239007105347900932096.0000 - val_loss: 350537395521405845504.0000 - val_mse: 350537395521405845504.0000
Epoch 35/500
389/389 [==============================] - 0s 93us/step - loss: 238686205649126948864.0000 - mse: 238686223874450784256.0000 - val_loss: 350191005378191294464.0000 - val_mse: 350191005378191294464.0000
Epoch 36/500
389/389 [==============================] - 0s 92us/step - loss: 238414304620451266560.0000 - mse: 238414319046948290560.0000 - val_loss: 349834059923350093824.0000 - val_mse: 349834059923350093824.0000
Epoch 37/500
389/389 [==============================] - 0s 95us/step - loss: 238231831547506884608.0000 - mse: 238231835301109563392.0000 - val_loss: 349457376035767058432.0000 - val_mse: 349457376035767058432.0000
Epoch 38/500
389/389 [==============================] - 0s 90us/step - loss: 237744782696369127424.0000 - mse: 237744778038283862016.0000 - val_loss: 349077032973486784512.0000 - val_mse: 349077032973486784512.0000

Epoch 39/500
389/389 [==============================] - 0s 92us/step - loss: 237469522283744985088.0000 - mse: 237469513103246884864.0000 - val_loss: 348682229134278000640.0000 - val_mse: 348682229134278000640.0000
Epoch 40/500
389/389 [==============================] - 0s 94us/step - loss: 237117979936449986560.0000 - mse: 237117968449521319936.0000 - val_loss: 348260157406700371968.0000 - val_mse: 348260157406700371968.0000
Epoch 41/500
389/389 [==============================] - 0s 90us/step - loss: 236773466232781340672.0000 - mse: 236773478262399565824.0000 - val_loss: 347814476965451137024.0000 - val_mse: 347814476965451137024.0000
Epoch 42/500
389/389 [==============================] - 0s 94us/step - loss: 236464100043536695296.0000 - mse: 236464102078622466048.0000 - val_loss: 347343393407553765376.0000 - val_mse: 347343393407553765376.0000
Epoch 43/500
389/389 [==============================] - 0s 95us/step - loss: 235983635418513014784.0000 - mse: 235983641885563420672.0000 - val_loss: 346848349292263899136.0000 - val_mse: 346848349292263899136.0000
Epoch 44/500
389/389 [==============================] - 0s 92us/step - loss: 235559679178882514944.0000 - mse: 235559652609706950656.0000 - val_loss: 346300563803212873728.0000 - val_mse: 346300563803212873728.0000
Epoch 45/500
389/389 [==============================] - 0s 92us/step - loss: 235144813893593038848.0000 - mse: 235144811270593576960.0000 - val_loss: 345737684218535739392.0000 - val_mse: 345737684218535739392.0000
Epoch 46/500
389/389 [==============================] - 0s 91us/step - loss: 234788135442007359488.0000 - mse: 234788147290729086976.0000 - val_loss: 345144440520745943040.0000 - val_mse: 345144440520745943040.0000
Epoch 47/500
389/389 [==============================] - 0s 92us/step - loss: 234288346863380955136.0000 - mse: 234288335693021184000.0000 - val_loss: 344512001432449187840.0000 - val_mse: 344512001432449187840.0000
Epoch 48/500
389/389 [==============================] - 0s 90us/step - loss: 233817359768550014976.0000 - mse: 233817357688240078848.0000 - val_loss: 343840789166110539776.0000 - val_mse: 343840789166110539776.0000
Epoch 49/500
389/389 [==============================] - 0s 95us/step - loss: 233334650048189726720.0000 - mse: 233334645695367348224.0000 - val_loss: 343110854182755631104.0000 - val_mse: 343110854182755631104.0000
Epoch 50/500
389/389 [==============================] - 0s 92us/step - loss: 232836578573197934592.0000 - mse: 232836593316263886848.0000 - val_loss: 342366951003681456128.0000 - val_mse: 342366951003681456128.0000
Epoch 51/500
389/389 [==============================] - 0s 97us/step - loss: 232240284168749842432.0000 - mse: 232240288578102362112.0000 - val_loss: 341539731231500926976.0000 - val_mse: 341539731231500926976.0000
Epoch 52/500
389/389 [==============================] - 0s 95us/step - loss: 231612646774924410880.0000 - mse: 231612652156595732480.0000 - val_loss: 340697804391787266048.0000 - val_mse: 340697804391787266048.0000
Epoch 53/500
389/389 [==============================] - 0s 94us/step - loss: 230878819622161481728.0000 - mse: 230878829300125007872.0000 - val_loss: 339783573667431055360.0000 - val_mse: 339783573667431055360.0000
Epoch 54/500
389/389 [==============================] - 0s 98us/step - loss: 230094296311631380480.0000 - mse: 230094305763474276352.0000 - val_loss: 338765971257877856256.0000 - val_mse: 338765971257877856256.0000
Epoch 55/500
389/389 [==============================] - 0s 95us/step - loss: 229559951139658006528.0000 - mse: 229559943112375140352.0000 - val_loss: 337725534190839005184.0000 - val_mse: 337725534190839005184.0000
Epoch 56/500
389/389 [==============================] - 0s 92us/step - loss: 228794709249437630464.0000 - mse: 228794718203815133184.0000 - val_loss: 336597417668554784768.0000 - val_mse: 336597417668554784768.0000
Epoch 57/500
389/389 [==============================] - 0s 92us/step - loss: 228074523141047320576.0000 - mse: 228074511699342786560.0000 - val_loss: 335381093925443862528.0000 - val_mse: 335381093925443862528.0000
Epoch 58/500
389/389 [==============================] - 0s 95us/step - loss: 227128111763390955520.0000 - mse: 227128104866711339008.0000 - val_loss: 334164312785495785472.0000 - val_mse: 334164312785495785472.0000
Epoch 59/500
389/389 [==============================] - 0s 95us/step - loss: 226318816823333126144.0000 - mse: 226318793939924025344.0000 - val_loss: 332792122274031337472.0000 - val_mse: 332792122274031337472.0000
Epoch 60/500
389/389 [==============================] - 0s 90us/step - loss: 225430376582898974720.0000 - mse: 225430370952494972928.0000 - val_loss: 331358570217643966464.0000 - val_mse: 331358570217643966464.0000
Epoch 61/500
389/389 [==============================] - 0s 95us/step - loss: 224248578816399966208.0000 - mse: 224248580670589239296.0000 - val_loss: 329877026677727428608.0000 - val_mse: 329877026677727428608.0000
Epoch 62/500
389/389 [==============================] - 0s 92us/step - loss: 223194634025719758848.0000 - mse: 223194650396854321152.0000 - val_loss: 328347139810560835584.0000 - val_mse: 328347139810560835584.0000
Epoch 63/500
389/389 [==============================] - 0s 93us/step - loss: 222111187048594800640.0000 - mse: 222111182842750828544.0000 - val_loss: 326739917693542989824.0000 - val_mse: 326739917693542989824.0000
Epoch 64/500
389/389 [==============================] - 0s 94us/step - loss: 220968442736674963456.0000 - mse: 220968429621677654016.0000 - val_loss: 325065000844626231296.0000 - val_mse: 325065000844626231296.0000
Epoch 65/500
389/389 [==============================] - 0s 95us/step - loss: 219634167863324966912.0000 - mse: 219634185455511011328.0000 - val_loss: 323337905571901734912.0000 - val_mse: 323337905571901734912.0000
Epoch 66/500
389/389 [==============================] - 0s 94us/step - loss: 218717813950923931648.0000 - mse: 218717808484457381888.0000 - val_loss: 321483865084680732672.0000 - val_mse: 321483865084680732672.0000
Epoch 67/500
389/389 [==============================] - 0s 91us/step - loss: 217452215269165826048.0000 - mse: 217452226620422094848.0000 - val_loss: 319603788162113994752.0000 - val_mse: 319603788162113994752.0000
Epoch 68/500
389/389 [==============================] - 0s 90us/step - loss: 216145389859061170176.0000 - mse: 216145391080112652288.0000 - val_loss: 317597997478073860096.0000 - val_mse: 317597997478073860096.0000
Epoch 69/500
389/389 [==============================] - 0s 95us/step - loss: 215204195791271460864.0000 - mse: 215204226718922440704.0000 - val_loss: 315296130302906204160.0000 - val_mse: 315296130302906204160.0000
Epoch 70/500
389/389 [==============================] - 0s 92us/step - loss: 213520179208879734784.0000 - mse: 213520179525448630272.0000 - val_loss: 313032227065222397952.0000 - val_mse: 313032227065222397952.0000
Epoch 71/500
389/389 [==============================] - 0s 92us/step - loss: 211965985277046947840.0000 - mse: 211965997849354698752.0000 - val_loss: 310362436911121825792.0000 - val_mse: 310362436911121825792.0000
Epoch 72/500
389/389 [==============================] - 0s 90us/step - loss: 210400566083345678336.0000 - mse: 210400574766378385408.0000 - val_loss: 307749223227340095488.0000 - val_mse: 307749223227340095488.0000
Epoch 73/500
389/389 [==============================] - 0s 89us/step - loss: 208573106620427599872.0000 - mse: 208573116072270495744.0000 - val_loss: 304762527433835413504.0000 - val_mse: 304762527433835413504.0000
Epoch 74/500
389/389 [==============================] - 0s 90us/step - loss: 207480319515318812672.0000 - mse: 207480324659563462656.0000 - val_loss: 301482781005202849792.0000 - val_mse: 301482781005202849792.0000
Epoch 75/500
389/389 [==============================] - 0s 92us/step - loss: 204854270172365553664.0000 - mse: 204854268679969308672.0000 - val_loss: 298216334269219864576.0000 - val_mse: 298216334269219864576.0000
Epoch 76/500
389/389 [==============================] - 0s 92us/step - loss: 203341390404078960640.0000 - mse: 203341393456707665920.0000 - val_loss: 294565076055701323776.0000 - val_mse: 294565076055701323776.0000
Epoch 77/500
389/389 [==============================] - 0s 87us/step - loss: 201476223876727799808.0000 - mse: 201476234707906592768.0000 - val_loss: 290631164189007151104.0000 - val_mse: 290631164189007151104.0000
Epoch 78/500
389/389 [==============================] - 0s 93us/step - loss: 199175595593952395264.0000 - mse: 199175598985762045952.0000 - val_loss: 286707807633939628032.0000 - val_mse: 286707807633939628032.0000
Epoch 79/500
389/389 [==============================] - 0s 92us/step - loss: 196195257962448748544.0000 - mse: 196195253971419398144.0000 - val_loss: 282016288275242680320.0000 - val_mse: 282016288275242680320.0000
Epoch 80/500
389/389 [==============================] - 0s 95us/step - loss: 194108822492904751104.0000 - mse: 194108820706551660544.0000 - val_loss: 277258041754879262720.0000 - val_mse: 277258041754879262720.0000
Epoch 81/500
389/389 [==============================] - 0s 97us/step - loss: 190905560625651482624.0000 - mse: 190905547510654173184.0000 - val_loss: 272540380407720312832.0000 - val_mse: 272540380407720312832.0000
Epoch 82/500
389/389 [==============================] - 0s 92us/step - loss: 188152746048927694848.0000 - mse: 188152757422796046336.0000 - val_loss: 267541156122920484864.0000 - val_mse: 267541156122920484864.0000
Epoch 83/500
389/389 [==============================] - 0s 89us/step - loss: 185209836595961823232.0000 - mse: 185209830988169871360.0000 - val_loss: 262680839739127365632.0000 - val_mse: 262680839739127365632.0000
Epoch 84/500
389/389 [==============================] - 0s 90us/step - loss: 184746734576693510144.0000 - mse: 184746734282736664576.0000 - val_loss: 257283187624793604096.0000 - val_mse: 257283187624793604096.0000
Epoch 85/500
389/389 [==============================] - 0s 95us/step - loss: 180403875906426109952.0000 - mse: 180403874459253997568.0000 - val_loss: 251867345190089916416.0000 - val_mse: 251867345190089916416.0000
Epoch 86/500
389/389 [==============================] - 0s 94us/step - loss: 178245161713814142976.0000 - mse: 178245172494115799040.0000 - val_loss: 246369241693442539520.0000 - val_mse: 246369241693442539520.0000
Epoch 87/500
389/389 [==============================] - 0s 91us/step - loss: 175082729133958791168.0000 - mse: 175082730762027401216.0000 - val_loss: 241030013228962283520.0000 - val_mse: 241030013228962283520.0000
Epoch 88/500
389/389 [==============================] - 0s 94us/step - loss: 171886466627708583936.0000 - mse: 171886459256175591424.0000 - val_loss: 235936142983243497472.0000 - val_mse: 235936142983243497472.0000
Epoch 89/500
389/389 [==============================] - 0s 95us/step - loss: 170184110875380449280.0000 - mse: 170184098597029543936.0000 - val_loss: 230366017076930281472.0000 - val_mse: 230366017076930281472.0000
Epoch 90/500
389/389 [==============================] - 0s 95us/step - loss: 166781974768964009984.0000 - mse: 166781980922272022528.0000 - val_loss: 224846345560192450560.0000 - val_mse: 224846345560192450560.0000
Epoch 91/500
389/389 [==============================] - 0s 90us/step - loss: 163915437453020135424.0000 - mse: 163915439759450701824.0000 - val_loss: 219724468554290954240.0000 - val_mse: 219724468554290954240.0000
Epoch 92/500
389/389 [==============================] - 0s 94us/step - loss: 161042026496324370432.0000 - mse: 161042037644072058880.0000 - val_loss: 214709868698888306688.0000 - val_mse: 214709868698888306688.0000
Epoch 93/500
389/389 [==============================] - 0s 92us/step - loss: 158412597916030173184.0000 - mse: 158412586372571332608.0000 - val_loss: 209680333077533949952.0000 - val_mse: 209680333077533949952.0000
Epoch 94/500
389/389 [==============================] - 0s 96us/step - loss: 156809979875347529728.0000 - mse: 156809973408297123840.0000 - val_loss: 204533527944007516160.0000 - val_mse: 204533527944007516160.0000
Epoch 95/500
389/389 [==============================] - 0s 95us/step - loss: 154813369791177392128.0000 - mse: 154813383437558218752.0000 - val_loss: 199867147819168038912.0000 - val_mse: 199867147819168038912.0000
Epoch 96/500
389/389 [==============================] - 0s 92us/step - loss: 152324036414857445376.0000 - mse: 152324036335715221504.0000 - val_loss: 195460956125925474304.0000 - val_mse: 195460956125925474304.0000
Epoch 97/500
389/389 [==============================] - 0s 90us/step - loss: 150755720581798133760.0000 - mse: 150755710542041579520.0000 - val_loss: 191191508494806155264.0000 - val_mse: 191191508494806155264.0000
Epoch 98/500
389/389 [==============================] - 0s 92us/step - loss: 146934485264770465792.0000 - mse: 146934485423054913536.0000 - val_loss: 187263050205785751552.0000 - val_mse: 187263050205785751552.0000
Epoch 99/500
389/389 [==============================] - 0s 92us/step - loss: 146063673231399206912.0000 - mse: 146063663417763299328.0000 - val_loss: 183596469198222524416.0000 - val_mse: 183596469198222524416.0000
Epoch 100/500
389/389 [==============================] - 0s 92us/step - loss: 142349026821468553216.0000 - mse: 142349020557926727680.0000 - val_loss: 179801588377837371392.0000 - val_mse: 179801588377837371392.0000
Epoch 101/500
389/389 [==============================] - 0s 90us/step - loss: 141614815161857785856.0000 - mse: 141614810673363025920.0000 - val_loss: 176210002859381489664.0000 - val_mse: 176210002859381489664.0000
Epoch 102/500
389/389 [==============================] - 0s 92us/step - loss: 139079874947700277248.0000 - mse: 139079873421385924608.0000 - val_loss: 172600508495532392448.0000 - val_mse: 172600508495532392448.0000
Epoch 103/500
389/389 [==============================] - 0s 92us/step - loss: 137811779424840400896.0000 - mse: 137811784670839308288.0000 - val_loss: 169315783478249259008.0000 - val_mse: 169315783478249259008.0000
Epoch 104/500
389/389 [==============================] - 0s 97us/step - loss: 137018689352844476416.0000 - mse: 137018693739584946176.0000 - val_loss: 166095551415004954624.0000 - val_mse: 166095551415004954624.0000
Epoch 105/500
389/389 [==============================] - 0s 95us/step - loss: 136115530716232974336.0000 - mse: 136115537296343695360.0000 - val_loss: 163828534360391286784.0000 - val_mse: 163828534360391286784.0000
Epoch 106/500
389/389 [==============================] - 0s 92us/step - loss: 135843465959252525056.0000 - mse: 135843456546980757504.0000 - val_loss: 160954780401291755520.0000 - val_mse: 160954780401291755520.0000
Epoch 107/500
389/389 [==============================] - 0s 95us/step - loss: 134151187968711606272.0000 - mse: 134151185006531182592.0000 - val_loss: 158204523588224024576.0000 - val_mse: 158204523588224024576.0000
Epoch 108/500
389/389 [==============================] - 0s 92us/step - loss: 129688731422008655872.0000 - mse: 129688733502318575616.0000 - val_loss: 156043253163923341312.0000 - val_mse: 156043253163923341312.0000
Epoch 109/500
389/389 [==============================] - 0s 90us/step - loss: 131413608903464206336.0000 - mse: 131413603363508453376.0000 - val_loss: 154169562204890726400.0000 - val_mse: 154169562204890726400.0000
Epoch 110/500
389/389 [==============================] - 0s 88us/step - loss: 129031690814744068096.0000 - mse: 129031691741838704640.0000 - val_loss: 152287356627812614144.0000 - val_mse: 152287356627812614144.0000
Epoch 111/500
389/389 [==============================] - 0s 87us/step - loss: 128716371502100578304.0000 - mse: 128716369399178592256.0000 - val_loss: 151076292948328972288.0000 - val_mse: 151076292948328972288.0000
Epoch 112/500
389/389 [==============================] - 0s 92us/step - loss: 128839128939672141824.0000 - mse: 128839127673396527104.0000 - val_loss: 149918938212838932480.0000 - val_mse: 149918938212838932480.0000
Epoch 113/500
389/389 [==============================] - 0s 93us/step - loss: 125342438634920247296.0000 - mse: 125342434406464225280.0000 - val_loss: 148636116006480117760.0000 - val_mse: 148636116006480117760.0000
Epoch 114/500
389/389 [==============================] - 0s 90us/step - loss: 126180355518982815744.0000 - mse: 126180359023852781568.0000 - val_loss: 147150016090378076160.0000 - val_mse: 147150016090378076160.0000
Epoch 115/500

389/389 [==============================] - 0s 92us/step - loss: 124576791966136467456.0000 - mse: 124576787285439152128.0000 - val_loss: 145651021101905477632.0000 - val_mse: 145651021101905477632.0000
Epoch 116/500
389/389 [==============================] - 0s 93us/step - loss: 124552502787613147136.0000 - mse: 124552501272604835840.0000 - val_loss: 144026848913633837056.0000 - val_mse: 144026848913633837056.0000
Epoch 117/500
389/389 [==============================] - 0s 92us/step - loss: 124331124120378212352.0000 - mse: 124331129999514927104.0000 - val_loss: 142694865343373901824.0000 - val_mse: 142694865343373901824.0000
Epoch 118/500
389/389 [==============================] - 0s 92us/step - loss: 122037413342933024768.0000 - mse: 122037416802578857984.0000 - val_loss: 141699561029632000000.0000 - val_mse: 141699561029632000000.0000
Epoch 119/500
389/389 [==============================] - 0s 90us/step - loss: 119337747151475212288.0000 - mse: 119337737524388823040.0000 - val_loss: 141235619899268661248.0000 - val_mse: 141235619899268661248.0000
Epoch 120/500
389/389 [==============================] - 0s 92us/step - loss: 120963287951899131904.0000 - mse: 120963281903171928064.0000 - val_loss: 139920014654216077312.0000 - val_mse: 139920014654216077312.0000
Epoch 121/500
389/389 [==============================] - 0s 90us/step - loss: 120309390562901049344.0000 - mse: 120309389143994007552.0000 - val_loss: 138305966769012998144.0000 - val_mse: 138305966769012998144.0000
Epoch 122/500
389/389 [==============================] - 0s 95us/step - loss: 121189961855827410944.0000 - mse: 121189966016447250432.0000 - val_loss: 136774030412172230656.0000 - val_mse: 136774030412172230656.0000
Epoch 123/500
389/389 [==============================] - 0s 87us/step - loss: 119035041108350631936.0000 - mse: 119035046371308601344.0000 - val_loss: 135890075839998459904.0000 - val_mse: 135890075839998459904.0000
Epoch 124/500
389/389 [==============================] - 0s 92us/step - loss: 116464491794047057920.0000 - mse: 116464502534777602048.0000 - val_loss: 135005206474150379520.0000 - val_mse: 135005206474150379520.0000
Epoch 125/500
389/389 [==============================] - 0s 95us/step - loss: 119843859097788694528.0000 - mse: 119843855920793649152.0000 - val_loss: 134352175732088635392.0000 - val_mse: 134352175732088635392.0000
Epoch 126/500
389/389 [==============================] - 0s 95us/step - loss: 117384446151961247744.0000 - mse: 117384433127412203520.0000 - val_loss: 133405900840852520960.0000 - val_mse: 133405900840852520960.0000
Epoch 127/500
389/389 [==============================] - 0s 95us/step - loss: 114517714199847190528.0000 - mse: 114517707246637416448.0000 - val_loss: 132467375307568971776.0000 - val_mse: 132467375307568971776.0000
Epoch 128/500
389/389 [==============================] - 0s 92us/step - loss: 114910783049278455808.0000 - mse: 114910778255520825344.0000 - val_loss: 131861236537408618496.0000 - val_mse: 131861236537408618496.0000
Epoch 129/500
389/389 [==============================] - 0s 90us/step - loss: 113390857994886201344.0000 - mse: 113390866157841416192.0000 - val_loss: 131422241126856261632.0000 - val_mse: 131422241126856261632.0000
Epoch 130/500
389/389 [==============================] - 0s 92us/step - loss: 114099063734132015104.0000 - mse: 114099057199245426688.0000 - val_loss: 130342459135729074176.0000 - val_mse: 130342459135729074176.0000
Epoch 131/500
389/389 [==============================] - 0s 95us/step - loss: 111518039771088240640.0000 - mse: 111518037215924977664.0000 - val_loss: 129363049362078302208.0000 - val_mse: 129363049362078302208.0000
Epoch 132/500
389/389 [==============================] - 0s 97us/step - loss: 113398807514832158720.0000 - mse: 113398809029840470016.0000 - val_loss: 128449891761070800896.0000 - val_mse: 128449891761070800896.0000
Epoch 133/500
389/389 [==============================] - 0s 92us/step - loss: 110026388932375527424.0000 - mse: 110026386965125922816.0000 - val_loss: 128359300799035080704.0000 - val_mse: 128359300799035080704.0000
Epoch 134/500
389/389 [==============================] - 0s 92us/step - loss: 112515517714737479680.0000 - mse: 112515522960736387072.0000 - val_loss: 127110246793788522496.0000 - val_mse: 127110246793788522496.0000
Epoch 135/500
389/389 [==============================] - 0s 97us/step - loss: 110757995422137352192.0000 - mse: 110758002002248073216.0000 - val_loss: 126388078760572223488.0000 - val_mse: 126388078760572223488.0000
Epoch 136/500
389/389 [==============================] - 0s 94us/step - loss: 108912891132289122304.0000 - mse: 108912889549444612096.0000 - val_loss: 125477639152308584448.0000 - val_mse: 125477639152308584448.0000
Epoch 137/500
389/389 [==============================] - 0s 92us/step - loss: 110620138642940755968.0000 - mse: 110620149632404029440.0000 - val_loss: 125039452982314270720.0000 - val_mse: 125039452982314270720.0000
Epoch 138/500
389/389 [==============================] - 0s 97us/step - loss: 106343775575495131136.0000 - mse: 106343779476076232704.0000 - val_loss: 124865756533404729344.0000 - val_mse: 124865756533404729344.0000
Epoch 139/500
389/389 [==============================] - 0s 93us/step - loss: 108021459281826758656.0000 - mse: 108021467094294986752.0000 - val_loss: 124292805422217166848.0000 - val_mse: 124292805422217166848.0000
Epoch 140/500
389/389 [==============================] - 0s 92us/step - loss: 106572313957187289088.0000 - mse: 106572310768886218752.0000 - val_loss: 123389121213394583552.0000 - val_mse: 123389121213394583552.0000
Epoch 141/500
389/389 [==============================] - 0s 95us/step - loss: 102891678794142269440.0000 - mse: 102891682400766525440.0000 - val_loss: 123468585117757210624.0000 - val_mse: 123468585117757210624.0000
Epoch 142/500
389/389 [==============================] - 0s 98us/step - loss: 105763197177584254976.0000 - mse: 105763202152238415872.0000 - val_loss: 123343188015632613376.0000 - val_mse: 123343188015632613376.0000
Epoch 143/500
389/389 [==============================] - 0s 90us/step - loss: 105494770831772991488.0000 - mse: 105494771781479694336.0000 - val_loss: 122084634229922070528.0000 - val_mse: 122084634229922070528.0000
Epoch 144/500
389/389 [==============================] - 0s 95us/step - loss: 103930931299926409216.0000 - mse: 103930931995247378432.0000 - val_loss: 121708715602431967232.0000 - val_mse: 121708715602431967232.0000
Epoch 145/500
389/389 [==============================] - 0s 95us/step - loss: 102991771492585537536.0000 - mse: 102991781939359252480.0000 - val_loss: 121536356159661801472.0000 - val_mse: 121536356159661801472.0000
Epoch 146/500
389/389 [==============================] - 0s 95us/step - loss: 99698892632743198720.0000 - mse: 99698894147751510016.0000 - val_loss: 121467904963762978816.0000 - val_mse: 121467904963762978816.0000
Epoch 147/500
389/389 [==============================] - 0s 95us/step - loss: 101470716151545937920.0000 - mse: 101470717553493934080.0000 - val_loss: 121594867770445529088.0000 - val_mse: 121594867770445529088.0000
Epoch 148/500
389/389 [==============================] - 0s 95us/step - loss: 102939364347747155968.0000 - mse: 102939366021039915008.0000 - val_loss: 121610331301978570752.0000 - val_mse: 121610331301978570752.0000
Epoch 149/500
389/389 [==============================] - 0s 94us/step - loss: 101968072463473311744.0000 - mse: 101968075041248641024.0000 - val_loss: 120538931987501547520.0000 - val_mse: 120538931987501547520.0000
Epoch 150/500
389/389 [==============================] - 0s 91us/step - loss: 98134470404958011392.0000 - mse: 98134465023286706176.0000 - val_loss: 120180464808567504896.0000 - val_mse: 120180464808567504896.0000
Epoch 151/500
389/389 [==============================] - 0s 95us/step - loss: 100747551966447910912.0000 - mse: 100747546765673103360.0000 - val_loss: 120028952106259972096.0000 - val_mse: 120028952106259972096.0000
Epoch 152/500
389/389 [==============================] - 0s 92us/step - loss: 97759036387924475904.0000 - mse: 97759038977005846528.0000 - val_loss: 120658303765905932288.0000 - val_mse: 120658303765905932288.0000
Epoch 153/500

389/389 [==============================] - 0s 95us/step - loss: 100564065466004652032.0000 - mse: 100564069061322866688.0000 - val_loss: 120865706843276574720.0000 - val_mse: 120865706843276574720.0000
Epoch 154/500
389/389 [==============================] - 0s 95us/step - loss: 97182905183846531072.0000 - mse: 97182912476237266944.0000 - val_loss: 120544104090198605824.0000 - val_mse: 120544104090198605824.0000
Epoch 155/500
389/389 [==============================] - 0s 95us/step - loss: 94582999186079105024.0000 - mse: 94582998485105115136.0000 - val_loss: 120089302100485341184.0000 - val_mse: 120089302100485341184.0000
Epoch 156/500
389/389 [==============================] - 0s 93us/step - loss: 95508113187442933760.0000 - mse: 95508118772622819328.0000 - val_loss: 118960719385270943744.0000 - val_mse: 118960719385270943744.0000
Epoch 157/500
389/389 [==============================] - 0s 90us/step - loss: 95261276411019427840.0000 - mse: 95261282810233618432.0000 - val_loss: 119819218064238444544.0000 - val_mse: 119819218064238444544.0000
Epoch 158/500
389/389 [==============================] - 0s 97us/step - loss: 93569039693148897280.0000 - mse: 93569046454156132352.0000 - val_loss: 120266481802231676928.0000 - val_mse: 120266481802231676928.0000
Epoch 159/500
389/389 [==============================] - 0s 93us/step - loss: 95467791280850370560.0000 - mse: 95467788686115995648.0000 - val_loss: 120872743717694341120.0000 - val_mse: 120872743717694341120.0000
Epoch 160/500
389/389 [==============================] - 0s 92us/step - loss: 93852585584464691200.0000 - mse: 93852588512727007232.0000 - val_loss: 120438682915327442944.0000 - val_mse: 120438682915327442944.0000
Epoch 161/500
389/389 [==============================] - 0s 98us/step - loss: 94770500910784462848.0000 - mse: 94770496003966500864.0000 - val_loss: 119974838541987348480.0000 - val_mse: 119974838541987348480.0000
Epoch 162/500
389/389 [==============================] - 0s 92us/step - loss: 94909481860064968704.0000 - mse: 94909474273717387264.0000 - val_loss: 120234481615816884224.0000 - val_mse: 120234481615816884224.0000
Epoch 163/500
389/389 [==============================] - 0s 93us/step - loss: 94895390982590709760.0000 - mse: 94895391728788832256.0000 - val_loss: 120115804728761253888.0000 - val_mse: 120115804728761253888.0000
Epoch 164/500
389/389 [==============================] - 0s 92us/step - loss: 92079955097616351232.0000 - mse: 92079955866426540032.0000 - val_loss: 120258283843534979072.0000 - val_mse: 120258283843534979072.0000
Epoch 165/500
389/389 [==============================] - 0s 92us/step - loss: 93775639363874095104.0000 - mse: 93775640290968731648.0000 - val_loss: 120773180740775968768.0000 - val_mse: 120773180740775968768.0000
Epoch 166/500
389/389 [==============================] - 0s 91us/step - loss: 91957944536529436672.0000 - mse: 91957945260115492864.0000 - val_loss: 120929531294245715968.0000 - val_mse: 120929531294245715968.0000
Epoch 167/500
389/389 [==============================] - 0s 97us/step - loss: 93751879827733446656.0000 - mse: 93751873247622725632.0000 - val_loss: 121151008120451891200.0000 - val_mse: 121151008120451891200.0000
Epoch 168/500
389/389 [==============================] - 0s 94us/step - loss: 90428940625250582528.0000 - mse: 90428938002251120640.0000 - val_loss: 120759898640312434688.0000 - val_mse: 120759898640312434688.0000
Epoch 169/500
389/389 [==============================] - 0s 92us/step - loss: 91727615550687559680.0000 - mse: 91727619564328976384.0000 - val_loss: 121366336477635543040.0000 - val_mse: 121366336477635543040.0000
Epoch 170/500
389/389 [==============================] - 0s 92us/step - loss: 91828685881731891200.0000 - mse: 91828695469247168512.0000 - val_loss: 121212800673932902400.0000 - val_mse: 121212800673932902400.0000
Epoch 171/500
389/389 [==============================] - 0s 95us/step - loss: 89804153097728196608.0000 - mse: 89804151514883686400.0000 - val_loss: 121965218471052574720.0000 - val_mse: 121965218471052574720.0000
Epoch 172/500
389/389 [==============================] - 0s 95us/step - loss: 91331316398277066752.0000 - mse: 91331311593213394944.0000 - val_loss: 122691749366407888896.0000 - val_mse: 122691749366407888896.0000
Epoch 173/500
389/389 [==============================] - 0s 97us/step - loss: 89480617194046996480.0000 - mse: 89480613621340831744.0000 - val_loss: 122817858952067284992.0000 - val_mse: 122817858952067284992.0000
Epoch 174/500
389/389 [==============================] - 0s 92us/step - loss: 89536737081562988544.0000 - mse: 89536732694822518784.0000 - val_loss: 124124659308004638720.0000 - val_mse: 124124659308004638720.0000
Epoch 175/500
389/389 [==============================] - 0s 95us/step - loss: 90833771761771970560.0000 - mse: 90833769387505221632.0000 - val_loss: 124524468124143058944.0000 - val_mse: 124524468124143058944.0000
Epoch 176/500
389/389 [==============================] - 0s 98us/step - loss: 88486426434024816640.0000 - mse: 88486426411412750336.0000 - val_loss: 124644033416593932288.0000 - val_mse: 124644033416593932288.0000
Epoch 177/500
389/389 [==============================] - 0s 95us/step - loss: 86179505937333993472.0000 - mse: 86179501482757324800.0000 - val_loss: 124638834925617807360.0000 - val_mse: 124638834925617807360.0000
Epoch 178/500
389/389 [==============================] - 0s 96us/step - loss: 86099754362289045504.0000 - mse: 86099756103417987072.0000 - val_loss: 125483989931470618624.0000 - val_mse: 125483989931470618624.0000
Epoch 179/500
389/389 [==============================] - 0s 92us/step - loss: 88036605882082213888.0000 - mse: 88036603010350055424.0000 - val_loss: 125679263196563636224.0000 - val_mse: 125679263196563636224.0000
Epoch 180/500
389/389 [==============================] - 0s 93us/step - loss: 87080410411171069952.0000 - mse: 87080406126184890368.0000 - val_loss: 126187906071665836032.0000 - val_mse: 126187906071665836032.0000
Epoch 181/500
389/389 [==============================] - 0s 92us/step - loss: 88184078882568044544.0000 - mse: 88184078305960394752.0000 - val_loss: 126331818949602181120.0000 - val_mse: 126331818949602181120.0000
Epoch 182/500
389/389 [==============================] - 0s 91us/step - loss: 86868273170259181568.0000 - mse: 86868279546861322240.0000 - val_loss: 125437106755662249984.0000 - val_mse: 125437106755662249984.0000
Epoch 183/500
389/389 [==============================] - 0s 92us/step - loss: 84677751010738208768.0000 - mse: 84677753317168775168.0000 - val_loss: 126490975456746012672.0000 - val_mse: 126490975456746012672.0000
Epoch 184/500
389/389 [==============================] - 0s 95us/step - loss: 86608486509821181952.0000 - mse: 86608486939450408960.0000 - val_loss: 127589985707219746816.0000 - val_mse: 127589985707219746816.0000
Epoch 185/500
389/389 [==============================] - 0s 92us/step - loss: 84268762205255516160.0000 - mse: 84268761379915169792.0000 - val_loss: 128749170030058405888.0000 - val_mse: 128749170030058405888.0000
Epoch 186/500
389/389 [==============================] - 0s 97us/step - loss: 87187596830761828352.0000 - mse: 87187595315753517056.0000 - val_loss: 129487232603365834752.0000 - val_mse: 129487232603365834752.0000
Epoch 187/500
389/389 [==============================] - 0s 92us/step - loss: 85155119863259332608.0000 - mse: 85155117285484003328.0000 - val_loss: 128766164081777311744.0000 - val_mse: 128766164081777311744.0000
Epoch 188/500
389/389 [==============================] - 0s 94us/step - loss: 84523862119651147776.0000 - mse: 84523865669745246208.0000 - val_loss: 128699744783366619136.0000 - val_mse: 128699744783366619136.0000
Epoch 189/500
389/389 [==============================] - 0s 92us/step - loss: 85623494507156684800.0000 - mse: 85623491646730534912.0000 - val_loss: 130323881787266170880.0000 - val_mse: 130323881787266170880.0000
Epoch 190/500
389/389 [==============================] - 0s 97us/step - loss: 83497926197728641024.0000 - mse: 83497924564006993920.0000 - val_loss: 130929167336403369984.0000 - val_mse: 130929167336403369984.0000
Epoch 191/500
389/389 [==============================] - 0s 95us/step - loss: 82876384671611142144.0000 - mse: 82876383834964754432.0000 - val_loss: 130636750019973087232.0000 - val_mse: 130636750019973087232.0000
Epoch 192/500
389/389 [==============================] - 0s 92us/step - loss: 83735504142192607232.0000 - mse: 83735507036536832000.0000 - val_loss: 132370328013254950912.0000 - val_mse: 132370328013254950912.0000
Epoch 193/500
389/389 [==============================] - 0s 94us/step - loss: 83299639309762772992.0000 - mse: 83299634239007358976.0000 - val_loss: 132505233691936555008.0000 - val_mse: 132505233691936555008.0000
Epoch 194/500
389/389 [==============================] - 0s 94us/step - loss: 83277298833289920512.0000 - mse: 83277300958823972864.0000 - val_loss: 133050213227313496064.0000 - val_mse: 133050213227313496064.0000
Epoch 195/500
389/389 [==============================] - 0s 92us/step - loss: 82503027730970263552.0000 - mse: 82503024870544113664.0000 - val_loss: 134439776022496804864.0000 - val_mse: 134439776022496804864.0000
Epoch 196/500
389/389 [==============================] - 0s 95us/step - loss: 81887250975408766976.0000 - mse: 81887254378524442624.0000 - val_loss: 133894646953538486272.0000 - val_mse: 133894646953538486272.0000
Epoch 197/500
389/389 [==============================] - 0s 95us/step - loss: 78882715518121672704.0000 - mse: 78882711312277700608.0000 - val_loss: 133937316800789217280.0000 - val_mse: 133937316800789217280.0000
Epoch 198/500
389/389 [==============================] - 0s 96us/step - loss: 81387913846646587392.0000 - mse: 81387908973746716672.0000 - val_loss: 134373646995155845120.0000 - val_mse: 134373646995155845120.0000
Epoch 199/500
389/389 [==============================] - 0s 91us/step - loss: 78634864624531292160.0000 - mse: 78634863799190945792.0000 - val_loss: 135836780312376901632.0000 - val_mse: 135836780312376901632.0000
Epoch 200/500
389/389 [==============================] - 0s 95us/step - loss: 79399858573466288128.0000 - mse: 79399860009332375552.0000 - val_loss: 135939756173387890688.0000 - val_mse: 135939756173387890688.0000
Epoch 201/500
389/389 [==============================] - 0s 91us/step - loss: 79588454529882390528.0000 - mse: 79588457039821537280.0000 - val_loss: 136049469841653891072.0000 - val_mse: 136049469841653891072.0000
Epoch 202/500
389/389 [==============================] - 0s 97us/step - loss: 79856576641674215424.0000 - mse: 79856579547324481536.0000 - val_loss: 137180805733984239616.0000 - val_mse: 137180805733984239616.0000
Epoch 203/500
389/389 [==============================] - 0s 97us/step - loss: 78567540888771756032.0000 - mse: 78567538503198965760.0000 - val_loss: 137695262826574118912.0000 - val_mse: 137695262826574118912.0000
Epoch 204/500
389/389 [==============================] - 0s 92us/step - loss: 80280843073603125248.0000 - mse: 80280841502064640000.0000 - val_loss: 137739322456522358784.0000 - val_mse: 137739322456522358784.0000
Epoch 205/500
389/389 [==============================] - 0s 90us/step - loss: 79322328645047238656.0000 - mse: 79322331245434634240.0000 - val_loss: 137845939900044541952.0000 - val_mse: 137845939900044541952.0000
Epoch 206/500
389/389 [==============================] - 0s 92us/step - loss: 80670161214700748800.0000 - mse: 80670156579227566080.0000 - val_loss: 137962408967751598080.0000 - val_mse: 137962408967751598080.0000
Epoch 207/500
389/389 [==============================] - 0s 92us/step - loss: 77704050890561470464.0000 - mse: 77704052439487873024.0000 - val_loss: 139433511545250775040.0000 - val_mse: 139433511545250775040.0000
Epoch 208/500
389/389 [==============================] - 0s 92us/step - loss: 78482798712417042432.0000 - mse: 78482796943023013888.0000 - val_loss: 139859207263153553408.0000 - val_mse: 139859207263153553408.0000
Epoch 209/500
389/389 [==============================] - 0s 93us/step - loss: 80148079187042254848.0000 - mse: 80148082070080454656.0000 - val_loss: 140532002826236198912.0000 - val_mse: 140532002826236198912.0000
Epoch 210/500
389/389 [==============================] - 0s 93us/step - loss: 78790676256192479232.0000 - mse: 78790677790986338304.0000 - val_loss: 140543393766699958272.0000 - val_mse: 140543393766699958272.0000
Epoch 211/500
389/389 [==============================] - 0s 95us/step - loss: 78570854924225167360.0000 - mse: 78570854630268338176.0000 - val_loss: 139744655743725338624.0000 - val_mse: 139744655743725338624.0000
Epoch 212/500
389/389 [==============================] - 0s 92us/step - loss: 76848510491439366144.0000 - mse: 76848509247775834112.0000 - val_loss: 139798426260370096128.0000 - val_mse: 139798426260370096128.0000
Epoch 213/500
389/389 [==============================] - 0s 97us/step - loss: 72835618200235925504.0000 - mse: 72835621659881766912.0000 - val_loss: 141622190595408658432.0000 - val_mse: 141622190595408658432.0000
Epoch 214/500
389/389 [==============================] - 0s 92us/step - loss: 78633818466069299200.0000 - mse: 78633825860214325248.0000 - val_loss: 142711815414627696640.0000 - val_mse: 142711815414627696640.0000
Epoch 215/500
389/389 [==============================] - 0s 91us/step - loss: 80239358155053137920.0000 - mse: 80239359127371907072.0000 - val_loss: 142489379814282100736.0000 - val_mse: 142489379814282100736.0000
Epoch 216/500
389/389 [==============================] - 0s 94us/step - loss: 75172707294825218048.0000 - mse: 75172703993463832576.0000 - val_loss: 142682005455375433728.0000 - val_mse: 142682005455375433728.0000
Epoch 217/500
389/389 [==============================] - 0s 92us/step - loss: 77364487770501726208.0000 - mse: 77364488064458555392.0000 - val_loss: 144238016718817984512.0000 - val_mse: 144238016718817984512.0000
Epoch 218/500
389/389 [==============================] - 0s 95us/step - loss: 76578424945837178880.0000 - mse: 76578425211528937472.0000 - val_loss: 145359193123707682816.0000 - val_mse: 145359193123707682816.0000
Epoch 219/500
389/389 [==============================] - 0s 92us/step - loss: 74020258789379915776.0000 - mse: 74020257477880184832.0000 - val_loss: 146382231518748606464.0000 - val_mse: 146382231518748606464.0000
Epoch 220/500
389/389 [==============================] - 0s 93us/step - loss: 77078563677932683264.0000 - mse: 77078562264678662144.0000 - val_loss: 145631353037907820544.0000 - val_mse: 145631353037907820544.0000
Epoch 221/500
389/389 [==============================] - 0s 92us/step - loss: 75693645140722876416.0000 - mse: 75693652602704101376.0000 - val_loss: 145238123699350011904.0000 - val_mse: 145238123699350011904.0000
Epoch 222/500
389/389 [==============================] - 0s 92us/step - loss: 75207802428402204672.0000 - mse: 75207800404622442496.0000 - val_loss: 146268383686762168320.0000 - val_mse: 146268383686762168320.0000
Epoch 223/500
389/389 [==============================] - 0s 90us/step - loss: 74293521867056218112.0000 - mse: 74293516903708098560.0000 - val_loss: 146501955140873879552.0000 - val_mse: 146501955140873879552.0000
Epoch 224/500
389/389 [==============================] - 0s 90us/step - loss: 78594747961993592832.0000 - mse: 78594744818916655104.0000 - val_loss: 147760025141468200960.0000 - val_mse: 147760025141468200960.0000
Epoch 225/500
389/389 [==============================] - 0s 95us/step - loss: 74346417568156385280.0000 - mse: 74346416607143657472.0000 - val_loss: 146934098394961936384.0000 - val_mse: 146934098394961936384.0000
Epoch 226/500
389/389 [==============================] - 0s 92us/step - loss: 75056675861011103744.0000 - mse: 75056674730407886848.0000 - val_loss: 148008989758368776192.0000 - val_mse: 148008989758368776192.0000
Epoch 227/500
389/389 [==============================] - 0s 95us/step - loss: 74330705168243392512.0000 - mse: 74330697988912971776.0000 - val_loss: 148058247879293140992.0000 - val_mse: 148058247879293140992.0000
Epoch 228/500
389/389 [==============================] - 0s 90us/step - loss: 73183772485831917568.0000 - mse: 73183771021700759552.0000 - val_loss: 149084699158426681344.0000 - val_mse: 149084699158426681344.0000
Epoch 229/500

389/389 [==============================] - 0s 92us/step - loss: 75234916102492356608.0000 - mse: 75234909963316887552.0000 - val_loss: 149794754971551399936.0000 - val_mse: 149794754971551399936.0000
Epoch 230/500
389/389 [==============================] - 0s 95us/step - loss: 75046998598454231040.0000 - mse: 75046999028083458048.0000 - val_loss: 148905434782634082304.0000 - val_mse: 148905434782634082304.0000
Epoch 231/500
389/389 [==============================] - 0s 93us/step - loss: 71653943997362405376.0000 - mse: 71653950125231833088.0000 - val_loss: 148454265579338989568.0000 - val_mse: 148454265579338989568.0000
Epoch 232/500
389/389 [==============================] - 0s 95us/step - loss: 74724441819770355712.0000 - mse: 74724446296959090688.0000 - val_loss: 150690197241212174336.0000 - val_mse: 150690197241212174336.0000
Epoch 233/500
389/389 [==============================] - 0s 92us/step - loss: 76579413483106271232.0000 - mse: 76579419170040446976.0000 - val_loss: 150554332788391149568.0000 - val_mse: 150554332788391149568.0000
Epoch 234/500
389/389 [==============================] - 0s 95us/step - loss: 73863129679923412992.0000 - mse: 73863124072131461120.0000 - val_loss: 151332839797414690816.0000 - val_mse: 151332839797414690816.0000
Epoch 235/500
389/389 [==============================] - 0s 92us/step - loss: 75444617537917124608.0000 - mse: 75444617617059348480.0000 - val_loss: 150949154219785977856.0000 - val_mse: 150949154219785977856.0000
Epoch 236/500
389/389 [==============================] - 0s 92us/step - loss: 73936318691211886592.0000 - mse: 73936316362169253888.0000 - val_loss: 152757648537337987072.0000 - val_mse: 152757648537337987072.0000
Epoch 237/500
389/389 [==============================] - 0s 92us/step - loss: 75746584980572602368.0000 - mse: 75746578694418726912.0000 - val_loss: 153228925609281847296.0000 - val_mse: 153228925609281847296.0000
Epoch 238/500
389/389 [==============================] - 0s 90us/step - loss: 69844353808724967424.0000 - mse: 69844351898005536768.0000 - val_loss: 151689169525744336896.0000 - val_mse: 151689169525744336896.0000
Epoch 239/500
389/389 [==============================] - 0s 90us/step - loss: 69449249664342908928.0000 - mse: 69449253389680508928.0000 - val_loss: 152955613406895800320.0000 - val_mse: 152955613406895800320.0000
Epoch 240/500
389/389 [==============================] - 0s 96us/step - loss: 71371623125937438720.0000 - mse: 71371621927498022912.0000 - val_loss: 153214341687051026432.0000 - val_mse: 153214341687051026432.0000
Epoch 241/500
389/389 [==============================] - 0s 93us/step - loss: 73290994564648108032.0000 - mse: 73290995395641475072.0000 - val_loss: 154386122015097487360.0000 - val_mse: 154386122015097487360.0000
Epoch 242/500
389/389 [==============================] - 0s 90us/step - loss: 70607412668072230912.0000 - mse: 70607412967682080768.0000 - val_loss: 153620985067467702272.0000 - val_mse: 153620985067467702272.0000
Epoch 243/500
389/389 [==============================] - 0s 90us/step - loss: 73181801539163176960.0000 - mse: 73181796298817273856.0000 - val_loss: 152892879671461412864.0000 - val_mse: 152892879671461412864.0000
Epoch 244/500
389/389 [==============================] - 0s 95us/step - loss: 70532620681890791424.0000 - mse: 70532619788714246144.0000 - val_loss: 153592344988587393024.0000 - val_mse: 153592344988587393024.0000
Epoch 245/500
389/389 [==============================] - 0s 90us/step - loss: 71613041282938626048.0000 - mse: 71613039496585543680.0000 - val_loss: 154469702490994507776.0000 - val_mse: 154469702490994507776.0000
Epoch 246/500
389/389 [==============================] - 0s 92us/step - loss: 69957798806785466368.0000 - mse: 69957795109712953344.0000 - val_loss: 153472190357904031744.0000 - val_mse: 153472190357904031744.0000
Epoch 247/500
389/389 [==============================] - 0s 93us/step - loss: 72987103332784029696.0000 - mse: 72987099177817210880.0000 - val_loss: 155174023251468746752.0000 - val_mse: 155174023251468746752.0000
Epoch 248/500
389/389 [==============================] - 0s 96us/step - loss: 73764115147319197696.0000 - mse: 73764115249073487872.0000 - val_loss: 155342222142239408128.0000 - val_mse: 155342222142239408128.0000
Epoch 249/500
389/389 [==============================] - 0s 92us/step - loss: 70546996505293627392.0000 - mse: 70546997002759045120.0000 - val_loss: 156243452241108795392.0000 - val_mse: 156243452241108795392.0000
Epoch 250/500
389/389 [==============================] - 0s 94us/step - loss: 71365842939606556672.0000 - mse: 71365838496335921152.0000 - val_loss: 156211047434414981120.0000 - val_mse: 156211047434414981120.0000
Epoch 251/500
389/389 [==============================] - 0s 90us/step - loss: 72956639325224198144.0000 - mse: 72956633909634793472.0000 - val_loss: 156359683814304251904.0000 - val_mse: 156359683814304251904.0000
Epoch 252/500
389/389 [==============================] - 0s 95us/step - loss: 73144664259179921408.0000 - mse: 73144667990170533888.0000 - val_loss: 156693073332031979520.0000 - val_mse: 156693073332031979520.0000
Epoch 253/500
389/389 [==============================] - 0s 97us/step - loss: 71754447127385219072.0000 - mse: 71754445488010559488.0000 - val_loss: 156419198179692511232.0000 - val_mse: 156419198179692511232.0000
Epoch 254/500
389/389 [==============================] - 0s 97us/step - loss: 69887804654065410048.0000 - mse: 69887808995581755392.0000 - val_loss: 155632862647879204864.0000 - val_mse: 155632862647879204864.0000
Epoch 255/500
389/389 [==============================] - 0s 99us/step - loss: 69144887587116417024.0000 - mse: 69144886580879556608.0000 - val_loss: 157288727159309860864.0000 - val_mse: 157288727159309860864.0000
Epoch 256/500
389/389 [==============================] - 0s 96us/step - loss: 70021495804854050816.0000 - mse: 70021492017333272576.0000 - val_loss: 159368369840364453888.0000 - val_mse: 159368369840364453888.0000
Epoch 257/500
389/389 [==============================] - 0s 92us/step - loss: 71799771122216189952.0000 - mse: 71799767357307486208.0000 - val_loss: 159132916022345990144.0000 - val_mse: 159132916022345990144.0000
Epoch 258/500
389/389 [==============================] - 0s 95us/step - loss: 71407558523824701440.0000 - mse: 71407558365540253696.0000 - val_loss: 157872347931333361664.0000 - val_mse: 157872347931333361664.0000
Epoch 259/500
389/389 [==============================] - 0s 92us/step - loss: 67901920433017102336.0000 - mse: 67901923870050877440.0000 - val_loss: 158137673281255243776.0000 - val_mse: 158137673281255243776.0000
Epoch 260/500
389/389 [==============================] - 0s 96us/step - loss: 70337751313490739200.0000 - mse: 70337751143900250112.0000 - val_loss: 159537184457646669824.0000 - val_mse: 159537184457646669824.0000
Epoch 261/500
389/389 [==============================] - 0s 94us/step - loss: 65869945645545160704.0000 - mse: 65869942819037118464.0000 - val_loss: 160468901814931030016.0000 - val_mse: 160468901814931030016.0000
Epoch 262/500
389/389 [==============================] - 0s 97us/step - loss: 68006871062135701504.0000 - mse: 68006874453945352192.0000 - val_loss: 161250909668977410048.0000 - val_mse: 161250909668977410048.0000
Epoch 263/500
389/389 [==============================] - 0s 95us/step - loss: 68959205138658353152.0000 - mse: 68959205455227256832.0000 - val_loss: 160623167694354513920.0000 - val_mse: 160623167694354513920.0000
Epoch 264/500
389/389 [==============================] - 0s 95us/step - loss: 71264970837224128512.0000 - mse: 71264973697650262016.0000 - val_loss: 159731595705623511040.0000 - val_mse: 159731595705623511040.0000
Epoch 265/500
389/389 [==============================] - 0s 93us/step - loss: 70596371078349266944.0000 - mse: 70596365074846187520.0000 - val_loss: 160808518966518480896.0000 - val_mse: 160808518966518480896.0000
Epoch 266/500
389/389 [==============================] - 0s 92us/step - loss: 69125802349076725760.0000 - mse: 69125807855114387456.0000 - val_loss: 161801861751516430336.0000 - val_mse: 161801861751516430336.0000
Epoch 267/500
389/389 [==============================] - 0s 95us/step - loss: 68957973346454282240.0000 - mse: 68957969604157636608.0000 - val_loss: 162064266798554939392.0000 - val_mse: 162064266798554939392.0000
Epoch 268/500
389/389 [==============================] - 0s 91us/step - loss: 67954009652231077888.0000 - mse: 67954009934881882112.0000 - val_loss: 162986976956584558592.0000 - val_mse: 162986976956584558592.0000
Epoch 269/500
389/389 [==============================] - 0s 92us/step - loss: 69223695357208543232.0000 - mse: 69223695176312029184.0000 - val_loss: 162406663515537408000.0000 - val_mse: 162406663515537408000.0000
Epoch 270/500
389/389 [==============================] - 0s 95us/step - loss: 69754331291374305280.0000 - mse: 69754332682016260096.0000 - val_loss: 163485768207501885440.0000 - val_mse: 163485768207501885440.0000
Epoch 271/500
389/389 [==============================] - 0s 95us/step - loss: 68275014350125760512.0000 - mse: 68275014553634340864.0000 - val_loss: 164989020504997232640.0000 - val_mse: 164989020504997232640.0000
Epoch 272/500
389/389 [==============================] - 0s 93us/step - loss: 68355053935034023936.0000 - mse: 68355054602089922560.0000 - val_loss: 164238977652993556480.0000 - val_mse: 164238977652993556480.0000
Epoch 273/500
389/389 [==============================] - 0s 91us/step - loss: 67582042776938512384.0000 - mse: 67582040753158750208.0000 - val_loss: 165005434014576672768.0000 - val_mse: 165005434014576672768.0000
Epoch 274/500
389/389 [==============================] - 0s 97us/step - loss: 66054536259171287040.0000 - mse: 66054537627201175552.0000 - val_loss: 164618810541878542336.0000 - val_mse: 164618810541878542336.0000
Epoch 275/500
389/389 [==============================] - 0s 95us/step - loss: 69041796902042796032.0000 - mse: 69041791972612767744.0000 - val_loss: 163959719291724496896.0000 - val_mse: 163959719291724496896.0000
Epoch 276/500
389/389 [==============================] - ETA: 0s - loss: 77231499934055792640.0000 - mse: 77231499934055792640.000 - 0s 92us/step - loss: 67674705580673990656.0000 - mse: 67674707593147711488.0000 - val_loss: 165570917242788380672.0000 - val_mse: 165570917242788380672.0000
Epoch 277/500
389/389 [==============================] - 0s 92us/step - loss: 66693821398674972672.0000 - mse: 66693820075869208576.0000 - val_loss: 165435668516478910464.0000 - val_mse: 165435668516478910464.0000
Epoch 278/500
389/389 [==============================] - 0s 97us/step - loss: 67935687831401070592.0000 - mse: 67935687673116622848.0000 - val_loss: 166125598868768817152.0000 - val_mse: 166125598868768817152.0000
Epoch 279/500
389/389 [==============================] - 0s 90us/step - loss: 66785461877064245248.0000 - mse: 66785466569067593728.0000 - val_loss: 166970023798900785152.0000 - val_mse: 166970023798900785152.0000
Epoch 280/500
389/389 [==============================] - 0s 90us/step - loss: 66940328745586360320.0000 - mse: 66940334980863098880.0000 - val_loss: 167346514172437331968.0000 - val_mse: 167346514172437331968.0000
Epoch 281/500
389/389 [==============================] - 0s 92us/step - loss: 68330458702220066816.0000 - mse: 68330465124046340096.0000 - val_loss: 167319756457463775232.0000 - val_mse: 167319756457463775232.0000
Epoch 282/500
389/389 [==============================] - 0s 92us/step - loss: 69189605793438113792.0000 - mse: 69189605917804462080.0000 - val_loss: 167602498071569629184.0000 - val_mse: 167602498071569629184.0000
Epoch 283/500
389/389 [==============================] - 0s 91us/step - loss: 66149272928386285568.0000 - mse: 66149271549050355712.0000 - val_loss: 166251875580195635200.0000 - val_mse: 166251875580195635200.0000
Epoch 284/500
389/389 [==============================] - 0s 95us/step - loss: 68574807258391355392.0000 - mse: 68574807394063745024.0000 - val_loss: 164201629442021261312.0000 - val_mse: 164201629442021261312.0000
Epoch 285/500
389/389 [==============================] - 0s 97us/step - loss: 66012511398443343872.0000 - mse: 66012514292787576832.0000 - val_loss: 166128343249791746048.0000 - val_mse: 166128343249791746048.0000
Epoch 286/500
389/389 [==============================] - 0s 91us/step - loss: 66339642190722908160.0000 - mse: 66339645390330003456.0000 - val_loss: 168399019479102652416.0000 - val_mse: 168399019479102652416.0000
Epoch 287/500
389/389 [==============================] - 0s 95us/step - loss: 68984102807832649728.0000 - mse: 68984102796526616576.0000 - val_loss: 169847612854557999104.0000 - val_mse: 169847612854557999104.0000
Epoch 288/500
389/389 [==============================] - 0s 93us/step - loss: 66892055261349986304.0000 - mse: 66892057624310710272.0000 - val_loss: 168550329871270674432.0000 - val_mse: 168550329871270674432.0000
Epoch 289/500
389/389 [==============================] - 0s 97us/step - loss: 68349816845264101376.0000 - mse: 68349812130648686592.0000 - val_loss: 167184261440549683200.0000 - val_mse: 167184261440549683200.0000
Epoch 290/500
389/389 [==============================] - 0s 95us/step - loss: 67711417465544130560.0000 - mse: 67711422485422407680.0000 - val_loss: 167297449565559455744.0000 - val_mse: 167297449565559455744.0000
Epoch 291/500
389/389 [==============================] - 0s 92us/step - loss: 65303449227261231104.0000 - mse: 65303452438174367744.0000 - val_loss: 168959752817082368000.0000 - val_mse: 168959752817082368000.0000
Epoch 292/500
389/389 [==============================] - 0s 94us/step - loss: 63126972698473816064.0000 - mse: 63126973569038286848.0000 - val_loss: 170207214729491906560.0000 - val_mse: 170207214729491906560.0000
Epoch 293/500
389/389 [==============================] - 0s 92us/step - loss: 67105469009823162368.0000 - mse: 67105468433215520768.0000 - val_loss: 169599580623517777920.0000 - val_mse: 169599580623517777920.0000
Epoch 294/500
389/389 [==============================] - 0s 97us/step - loss: 65780511522373296128.0000 - mse: 65780512941280329728.0000 - val_loss: 170389874397191077888.0000 - val_mse: 170389874397191077888.0000
Epoch 295/500
389/389 [==============================] - 0s 95us/step - loss: 67612325192662769664.0000 - mse: 67612325701434212352.0000 - val_loss: 169796736252517548032.0000 - val_mse: 169796736252517548032.0000
Epoch 296/500
389/389 [==============================] - 0s 95us/step - loss: 64066021327947407360.0000 - mse: 64066018071810146304.0000 - val_loss: 169997322357795979264.0000 - val_mse: 169997322357795979264.0000
Epoch 297/500
389/389 [==============================] - 0s 95us/step - loss: 67530803579140579328.0000 - mse: 67530803511304388608.0000 - val_loss: 169570975729009557504.0000 - val_mse: 169570975729009557504.0000
Epoch 298/500
389/389 [==============================] - 0s 87us/step - loss: 66663888723749617664.0000 - mse: 66663891369361145856.0000 - val_loss: 170033878920396275712.0000 - val_mse: 170033878920396275712.0000
Epoch 299/500
389/389 [==============================] - 0s 95us/step - loss: 62787716480657104896.0000 - mse: 62787717057264746496.0000 - val_loss: 170570335041634697216.0000 - val_mse: 170570335041634697216.0000
Epoch 300/500
389/389 [==============================] - 0s 92us/step - loss: 64246616525479788544.0000 - mse: 64246615055695609856.0000 - val_loss: 171485550928409395200.0000 - val_mse: 171485550928409395200.0000
Epoch 301/500
389/389 [==============================] - 0s 92us/step - loss: 65290210869836136448.0000 - mse: 65290209920129433600.0000 - val_loss: 171183651423701172224.0000 - val_mse: 171183651423701172224.0000
Epoch 302/500
389/389 [==============================] - 0s 92us/step - loss: 65344977380078182400.0000 - mse: 65344978793332211712.0000 - val_loss: 171735148864007569408.0000 - val_mse: 171735148864007569408.0000
Epoch 303/500
389/389 [==============================] - 0s 92us/step - loss: 63591041620918681600.0000 - mse: 63591042242750447616.0000 - val_loss: 170828799438999257088.0000 - val_mse: 170828799438999257088.0000
Epoch 304/500
389/389 [==============================] - 0s 89us/step - loss: 64886218912245948416.0000 - mse: 64886218561758953472.0000 - val_loss: 172790979093835284480.0000 - val_mse: 172790979093835284480.0000

Epoch 305/500
389/389 [==============================] - 0s 95us/step - loss: 62806540798086561792.0000 - mse: 62806540696332271616.0000 - val_loss: 174182169166227701760.0000 - val_mse: 174182169166227701760.0000
Epoch 306/500
389/389 [==============================] - 0s 92us/step - loss: 63168622176321896448.0000 - mse: 63168623069498441728.0000 - val_loss: 174616819306827087872.0000 - val_mse: 174616819306827087872.0000
Epoch 307/500
389/389 [==============================] - 0s 95us/step - loss: 65202055034925613056.0000 - mse: 65202055475860865024.0000 - val_loss: 173491077729658863616.0000 - val_mse: 173491077729658863616.0000
Epoch 308/500
389/389 [==============================] - 0s 91us/step - loss: 64112677863035052032.0000 - mse: 64112676947246448640.0000 - val_loss: 172376032201605644288.0000 - val_mse: 172376032201605644288.0000
Epoch 309/500
389/389 [==============================] - 0s 95us/step - loss: 64965813887439429632.0000 - mse: 64965814407516913664.0000 - val_loss: 172399429809044717568.0000 - val_mse: 172399429809044717568.0000
Epoch 310/500
389/389 [==============================] - 0s 95us/step - loss: 62718014012260794368.0000 - mse: 62718012418110259200.0000 - val_loss: 172251585077527445504.0000 - val_mse: 172251585077527445504.0000
Epoch 311/500
389/389 [==============================] - 0s 90us/step - loss: 62169350033204731904.0000 - mse: 62169351717803524096.0000 - val_loss: 173600254836250509312.0000 - val_mse: 173600254836250509312.0000
Epoch 312/500
389/389 [==============================] - 0s 95us/step - loss: 66319498041016926208.0000 - mse: 66319497939262636032.0000 - val_loss: 176408864930427568128.0000 - val_mse: 176408864930427568128.0000
Epoch 313/500
389/389 [==============================] - 0s 90us/step - loss: 61849985704904400896.0000 - mse: 61849983172353196032.0000 - val_loss: 175114748540628238336.0000 - val_mse: 175114748540628238336.0000
Epoch 314/500
389/389 [==============================] - 0s 96us/step - loss: 63960859035774189568.0000 - mse: 63960856381683138560.0000 - val_loss: 175540813694437949440.0000 - val_mse: 175540813694437949440.0000
Epoch 315/500
389/389 [==============================] - 0s 90us/step - loss: 61936299888929988608.0000 - mse: 61936299233180123136.0000 - val_loss: 175725144619811340288.0000 - val_mse: 175725144619811340288.0000
Epoch 316/500
389/389 [==============================] - 0s 93us/step - loss: 63670166683497406464.0000 - mse: 63670171895578230784.0000 - val_loss: 177276194886789365760.0000 - val_mse: 177276194886789365760.0000
Epoch 317/500
389/389 [==============================] - 0s 90us/step - loss: 65957679901128417280.0000 - mse: 65957683846933643264.0000 - val_loss: 176355349500480454656.0000 - val_mse: 176355349500480454656.0000
Epoch 318/500
389/389 [==============================] - 0s 92us/step - loss: 61622634626179768320.0000 - mse: 61622630556008185856.0000 - val_loss: 176410448227171565568.0000 - val_mse: 176410448227171565568.0000
Epoch 319/500
389/389 [==============================] - 0s 88us/step - loss: 65038065470377205760.0000 - mse: 65038069913647841280.0000 - val_loss: 176283608565791326208.0000 - val_mse: 176283608565791326208.0000
Epoch 320/500
389/389 [==============================] - 0s 90us/step - loss: 63928909463638876160.0000 - mse: 63928904573779968000.0000 - val_loss: 177760226293615427584.0000 - val_mse: 177760226293615427584.0000
Epoch 321/500
389/389 [==============================] - 0s 95us/step - loss: 62677995339103846400.0000 - mse: 62677998990952235008.0000 - val_loss: 175864175666120359936.0000 - val_mse: 175864175666120359936.0000
Epoch 322/500
389/389 [==============================] - 0s 95us/step - loss: 61941317042456264704.0000 - mse: 61941321802295803904.0000 - val_loss: 175948231131040579584.0000 - val_mse: 175948231131040579584.0000
Epoch 323/500
389/389 [==============================] - 0s 90us/step - loss: 66115281642300416000.0000 - mse: 66115279047566032896.0000 - val_loss: 178582150817796587520.0000 - val_mse: 178582150817796587520.0000
Epoch 324/500
389/389 [==============================] - 0s 95us/step - loss: 63280163532523118592.0000 - mse: 63280166325113061376.0000 - val_loss: 178407794661910380544.0000 - val_mse: 178407794661910380544.0000
Epoch 325/500
389/389 [==============================] - 0s 92us/step - loss: 62135506403898908672.0000 - mse: 62135504351854067712.0000 - val_loss: 178527685409803075584.0000 - val_mse: 178527685409803075584.0000
Epoch 326/500
389/389 [==============================] - 0s 90us/step - loss: 64871735630660419584.0000 - mse: 64871735794597888000.0000 - val_loss: 179084354952806531072.0000 - val_mse: 179084354952806531072.0000
Epoch 327/500
389/389 [==============================] - 0s 90us/step - loss: 64556266439601561600.0000 - mse: 64556263918356398080.0000 - val_loss: 176529001968924884992.0000 - val_mse: 176529001968924884992.0000
Epoch 328/500
389/389 [==============================] - 0s 92us/step - loss: 62556483283587022848.0000 - mse: 62556480965850431488.0000 - val_loss: 176665517332629553152.0000 - val_mse: 176665517332629553152.0000
Epoch 329/500
389/389 [==============================] - 0s 95us/step - loss: 62382439535981527040.0000 - mse: 62382437071266512896.0000 - val_loss: 177371034361754812416.0000 - val_mse: 177371034361754812416.0000
Epoch 330/500
389/389 [==============================] - 0s 92us/step - loss: 62853150288774381568.0000 - mse: 62853151193256951808.0000 - val_loss: 177778223099938865152.0000 - val_mse: 177778223099938865152.0000
Epoch 331/500
389/389 [==============================] - 0s 92us/step - loss: 60312019179708637184.0000 - mse: 60312021491792216064.0000 - val_loss: 179594950560559661056.0000 - val_mse: 179594950560559661056.0000
Epoch 332/500
389/389 [==============================] - 0s 90us/step - loss: 58352123993466232832.0000 - mse: 58352128821141962752.0000 - val_loss: 181144065687072800768.0000 - val_mse: 181144065687072800768.0000
Epoch 333/500
389/389 [==============================] - 0s 95us/step - loss: 61624969231373008896.0000 - mse: 61624970316752093184.0000 - val_loss: 180987794298440253440.0000 - val_mse: 180987794298440253440.0000
Epoch 334/500
389/389 [==============================] - 0s 92us/step - loss: 59173565275220713472.0000 - mse: 59173565162160390144.0000 - val_loss: 180675955208616935424.0000 - val_mse: 180675955208616935424.0000
Epoch 335/500
389/389 [==============================] - 0s 92us/step - loss: 61801651332031815680.0000 - mse: 61801653039242674176.0000 - val_loss: 179225127625533947904.0000 - val_mse: 179225127625533947904.0000
Epoch 336/500
389/389 [==============================] - 0s 95us/step - loss: 60238833565882834944.0000 - mse: 60238833599800934400.0000 - val_loss: 178906304437850996736.0000 - val_mse: 178906304437850996736.0000
Epoch 337/500
389/389 [==============================] - 0s 105us/step - loss: 60952087810282119168.0000 - mse: 60952086792739225600.0000 - val_loss: 179857953741923680256.0000 - val_mse: 179857953741923680256.0000
Epoch 338/500
389/389 [==============================] - 0s 108us/step - loss: 60764977952651509760.0000 - mse: 60764976301970817024.0000 - val_loss: 182531244741047091200.0000 - val_mse: 182531244741047091200.0000
Epoch 339/500
389/389 [==============================] - 0s 92us/step - loss: 60660061626034487296.0000 - mse: 60660060902448431104.0000 - val_loss: 183424945384289468416.0000 - val_mse: 183424945384289468416.0000
Epoch 340/500
389/389 [==============================] - 0s 92us/step - loss: 58920733842689228800.0000 - mse: 58920734662376554496.0000 - val_loss: 182258812147963265024.0000 - val_mse: 182258812147963265024.0000
Epoch 341/500
389/389 [==============================] - 0s 94us/step - loss: 61628423314646827008.0000 - mse: 61628427181309820928.0000 - val_loss: 181183137932277448704.0000 - val_mse: 181183137932277448704.0000
Epoch 342/500
389/389 [==============================] - 0s 95us/step - loss: 59723349433331343360.0000 - mse: 59723351762373967872.0000 - val_loss: 181400207915879497728.0000 - val_mse: 181400207915879497728.0000
Epoch 343/500
389/389 [==============================] - 0s 100us/step - loss: 61636224329860341760.0000 - mse: 61636224917774008320.0000 - val_loss: 183669670284353339392.0000 - val_mse: 183669670284353339392.0000
Epoch 344/500
389/389 [==============================] - 0s 98us/step - loss: 60403176873565536256.0000 - mse: 60403179801827868672.0000 - val_loss: 185292549446950715392.0000 - val_mse: 185292549446950715392.0000
Epoch 345/500
389/389 [==============================] - 0s 97us/step - loss: 60459918717216817152.0000 - mse: 60459923397914132480.0000 - val_loss: 186148127823034843136.0000 - val_mse: 186148127823034843136.0000
Epoch 346/500
389/389 [==============================] - 0s 92us/step - loss: 58291198284777127936.0000 - mse: 58291202682823639040.0000 - val_loss: 183979415904037371904.0000 - val_mse: 183979415904037371904.0000
Epoch 347/500
389/389 [==============================] - 0s 92us/step - loss: 58917240227873947648.0000 - mse: 58917242613446737920.0000 - val_loss: 184830965669517328384.0000 - val_mse: 184830965669517328384.0000
Epoch 348/500
389/389 [==============================] - 0s 92us/step - loss: 59314584673834991616.0000 - mse: 59314584125492428800.0000 - val_loss: 184448247662121058304.0000 - val_mse: 184448247662121058304.0000
Epoch 349/500
389/389 [==============================] - 0s 90us/step - loss: 59543585466589560832.0000 - mse: 59543586009279102976.0000 - val_loss: 184361782067712753664.0000 - val_mse: 184361782067712753664.0000
Epoch 350/500
389/389 [==============================] - 0s 95us/step - loss: 60930095361744289792.0000 - mse: 60930092162137194496.0000 - val_loss: 183802526473360769024.0000 - val_mse: 183802526473360769024.0000
Epoch 351/500
389/389 [==============================] - 0s 92us/step - loss: 59832812661678915584.0000 - mse: 59832810343942324224.0000 - val_loss: 183642683870961205248.0000 - val_mse: 183642683870961205248.0000
Epoch 352/500
389/389 [==============================] - 0s 97us/step - loss: 59048458986855391232.0000 - mse: 59048458331105525760.0000 - val_loss: 182997138604061360128.0000 - val_mse: 182997138604061360128.0000
Epoch 353/500
389/389 [==============================] - 0s 93us/step - loss: 59114454433426350080.0000 - mse: 59114455417051152384.0000 - val_loss: 184890005045882388480.0000 - val_mse: 184890005045882388480.0000
Epoch 354/500
389/389 [==============================] - 0s 92us/step - loss: 57902078033160421376.0000 - mse: 57902081119707201536.0000 - val_loss: 184972617951546966016.0000 - val_mse: 184972617951546966016.0000
Epoch 355/500
389/389 [==============================] - 0s 103us/step - loss: 59661903997649780736.0000 - mse: 59661906654567333888.0000 - val_loss: 184909233305228935168.0000 - val_mse: 184909233305228935168.0000
Epoch 356/500
389/389 [==============================] - 0s 97us/step - loss: 58166270247314874368.0000 - mse: 58166271773629218816.0000 - val_loss: 185006394948752244736.0000 - val_mse: 185006394948752244736.0000
Epoch 357/500
389/389 [==============================] - 0s 95us/step - loss: 55054245640119861248.0000 - mse: 55054249246744117248.0000 - val_loss: 185610862461238378496.0000 - val_mse: 185610862461238378496.0000
Epoch 358/500
389/389 [==============================] - 0s 90us/step - loss: 58351018840128405504.0000 - mse: 58351016115374653440.0000 - val_loss: 187730685695218417664.0000 - val_mse: 187730685695218417664.0000
Epoch 359/500
389/389 [==============================] - 0s 97us/step - loss: 57100852151726604288.0000 - mse: 57100849404360785920.0000 - val_loss: 188188751035442921472.0000 - val_mse: 188188751035442921472.0000
Epoch 360/500
389/389 [==============================] - 0s 95us/step - loss: 54972508556236726272.0000 - mse: 54972511552335249408.0000 - val_loss: 187907856600871731200.0000 - val_mse: 187907856600871731200.0000
Epoch 361/500
389/389 [==============================] - 0s 98us/step - loss: 59076620922329530368.0000 - mse: 59076623420962635776.0000 - val_loss: 188555073125445795840.0000 - val_mse: 188555073125445795840.0000
Epoch 362/500
389/389 [==============================] - 0s 95us/step - loss: 58357997081463373824.0000 - mse: 58357995815187775488.0000 - val_loss: 189598377718809886720.0000 - val_mse: 189598377718809886720.0000
Epoch 363/500
389/389 [==============================] - 0s 95us/step - loss: 59728755559588126720.0000 - mse: 59728756961536114688.0000 - val_loss: 188932830136377540608.0000 - val_mse: 188932830136377540608.0000
Epoch 364/500
389/389 [==============================] - 0s 92us/step - loss: 61088162408322949120.0000 - mse: 61088162351792783360.0000 - val_loss: 190234282467757391872.0000 - val_mse: 190234282467757391872.0000
Epoch 365/500
389/389 [==============================] - 0s 90us/step - loss: 58017292227398746112.0000 - mse: 58017292346112081920.0000 - val_loss: 189546762244955570176.0000 - val_mse: 189546762244955570176.0000
Epoch 366/500
389/389 [==============================] - 0s 91us/step - loss: 58263452965282136064.0000 - mse: 58263451009338572800.0000 - val_loss: 188560667440607920128.0000 - val_mse: 188560667440607920128.0000
Epoch 367/500
389/389 [==============================] - 0s 92us/step - loss: 59881742240614686720.0000 - mse: 59881743009424867328.0000 - val_loss: 188472618549455618048.0000 - val_mse: 188472618549455618048.0000
Epoch 368/500
389/389 [==============================] - 0s 92us/step - loss: 57559711491977797632.0000 - mse: 57559706392957288448.0000 - val_loss: 189999004571599372288.0000 - val_mse: 189999004571599372288.0000
Epoch 369/500
389/389 [==============================] - 0s 95us/step - loss: 55619745940440137728.0000 - mse: 55619745669095358464.0000 - val_loss: 191985778102525493248.0000 - val_mse: 191985778102525493248.0000
Epoch 370/500
389/389 [==============================] - 0s 92us/step - loss: 55766810329617563648.0000 - mse: 55766811946380165120.0000 - val_loss: 194913540072781381632.0000 - val_mse: 194913540072781381632.0000
Epoch 371/500
389/389 [==============================] - 0s 93us/step - loss: 56664191809914806272.0000 - mse: 56664193754552336384.0000 - val_loss: 193132647895133061120.0000 - val_mse: 193132647895133061120.0000
Epoch 372/500
389/389 [==============================] - 0s 92us/step - loss: 56304628793813434368.0000 - mse: 56304627063990517760.0000 - val_loss: 191578554179969351680.0000 - val_mse: 191578554179969351680.0000
Epoch 373/500
389/389 [==============================] - 0s 92us/step - loss: 55353768989966639104.0000 - mse: 55353765010243321856.0000 - val_loss: 189981025357461979136.0000 - val_mse: 189981025357461979136.0000
Epoch 374/500
389/389 [==============================] - 0s 95us/step - loss: 56539153323824357376.0000 - mse: 56539148496148627456.0000 - val_loss: 191510894632442527744.0000 - val_mse: 191510894632442527744.0000
Epoch 375/500
389/389 [==============================] - 0s 93us/step - loss: 55533162955499888640.0000 - mse: 55533161327431254016.0000 - val_loss: 193854437696349405184.0000 - val_mse: 193854437696349405184.0000
Epoch 376/500
389/389 [==============================] - 0s 92us/step - loss: 56966410755255738368.0000 - mse: 56966414316655869952.0000 - val_loss: 194164341645707837440.0000 - val_mse: 194164341645707837440.0000
Epoch 377/500
389/389 [==============================] - 0s 92us/step - loss: 58512295216996622336.0000 - mse: 58512292480936837120.0000 - val_loss: 192211134005754462208.0000 - val_mse: 192211134005754462208.0000
Epoch 378/500
389/389 [==============================] - 0s 92us/step - loss: 56746404368980516864.0000 - mse: 56746402039937892352.0000 - val_loss: 191523666559510773760.0000 - val_mse: 191523666559510773760.0000
Epoch 379/500
389/389 [==============================] - 0s 90us/step - loss: 56101335159523917824.0000 - mse: 56101336160107757568.0000 - val_loss: 191644067480798756864.0000 - val_mse: 191644067480798756864.0000
Epoch 380/500
389/389 [==============================] - 0s 92us/step - loss: 54820219231273934848.0000 - mse: 54820224793841762304.0000 - val_loss: 192946205907434340352.0000 - val_mse: 192946205907434340352.0000
Epoch 381/500

389/389 [==============================] - 0s 91us/step - loss: 53738920321117577216.0000 - mse: 53738925476668243968.0000 - val_loss: 194619732973653590016.0000 - val_mse: 194619732973653590016.0000
Epoch 382/500
389/389 [==============================] - 0s 90us/step - loss: 55453326811334352896.0000 - mse: 55453327987161694208.0000 - val_loss: 194030359556793565184.0000 - val_mse: 194030359556793565184.0000
Epoch 383/500
389/389 [==============================] - 0s 92us/step - loss: 56534899847546511360.0000 - mse: 56534899983218900992.0000 - val_loss: 193575795061591900160.0000 - val_mse: 193575795061591900160.0000
Epoch 384/500
389/389 [==============================] - 0s 94us/step - loss: 56518201482486751232.0000 - mse: 56518200600616239104.0000 - val_loss: 194448490634697244672.0000 - val_mse: 194448490634697244672.0000
Epoch 385/500
389/389 [==============================] - 0s 92us/step - loss: 55319315179758034944.0000 - mse: 55319319509968355328.0000 - val_loss: 193590977118148231168.0000 - val_mse: 193590977118148231168.0000
Epoch 386/500
389/389 [==============================] - 0s 91us/step - loss: 55007992187690860544.0000 - mse: 55007994991586836480.0000 - val_loss: 192281801817094881280.0000 - val_mse: 192281801817094881280.0000
Epoch 387/500
389/389 [==============================] - 0s 94us/step - loss: 52782136959146065920.0000 - mse: 52782134856224079872.0000 - val_loss: 193619810711075028992.0000 - val_mse: 193619810711075028992.0000
Epoch 388/500
389/389 [==============================] - 0s 97us/step - loss: 55332212892087099392.0000 - mse: 55332214582338912256.0000 - val_loss: 195950142043262550016.0000 - val_mse: 195950142043262550016.0000
Epoch 389/500
389/389 [==============================] - 0s 91us/step - loss: 54975312350458667008.0000 - mse: 54975313107962822656.0000 - val_loss: 195575621994562977792.0000 - val_mse: 195575621994562977792.0000
Epoch 390/500
389/389 [==============================] - 0s 95us/step - loss: 56042248834860294144.0000 - mse: 56042248405231075328.0000 - val_loss: 193799321377472249856.0000 - val_mse: 193799321377472249856.0000
Epoch 391/500
389/389 [==============================] - 0s 92us/step - loss: 55291577209183952896.0000 - mse: 55291576632576311296.0000 - val_loss: 193171755324709797888.0000 - val_mse: 193171755324709797888.0000
Epoch 392/500
389/389 [==============================] - 0s 95us/step - loss: 53685382855713783808.0000 - mse: 53685383658442063872.0000 - val_loss: 193859381100627886080.0000 - val_mse: 193859381100627886080.0000
Epoch 393/500
389/389 [==============================] - 0s 92us/step - loss: 53915845784118673408.0000 - mse: 53915845693670424576.0000 - val_loss: 196894701696359333888.0000 - val_mse: 196894701696359333888.0000
Epoch 394/500
389/389 [==============================] - 0s 92us/step - loss: 53654552736220471296.0000 - mse: 53654553352399224832.0000 - val_loss: 197236781753993003008.0000 - val_mse: 197236781753993003008.0000
Epoch 395/500
389/389 [==============================] - 0s 92us/step - loss: 53840383762900197376.0000 - mse: 53840384011632902144.0000 - val_loss: 196566941678165819392.0000 - val_mse: 196566941678165819392.0000
Epoch 396/500
389/389 [==============================] - 0s 92us/step - loss: 53948312073015394304.0000 - mse: 53948312073015394304.0000 - val_loss: 195394475254863626240.0000 - val_mse: 195394475254863626240.0000
Epoch 397/500
389/389 [==============================] - 0s 91us/step - loss: 54358097970724577280.0000 - mse: 54358100056687509504.0000 - val_loss: 197657481291059167232.0000 - val_mse: 197657481291059167232.0000
Epoch 398/500
389/389 [==============================] - 0s 92us/step - loss: 56403715447596818432.0000 - mse: 56403719449932201984.0000 - val_loss: 198820324788595064832.0000 - val_mse: 198820324788595064832.0000
Epoch 399/500
389/389 [==============================] - 0s 95us/step - loss: 54930908112650125312.0000 - mse: 54930910430386716672.0000 - val_loss: 199522728000790462464.0000 - val_mse: 199522728000790462464.0000
Epoch 400/500
389/389 [==============================] - 0s 92us/step - loss: 53615263285178941440.0000 - mse: 53615261204869021696.0000 - val_loss: 200107193197744095232.0000 - val_mse: 200107193197744095232.0000
Epoch 401/500
389/389 [==============================] - 0s 92us/step - loss: 55942075807058518016.0000 - mse: 55942078497894170624.0000 - val_loss: 197385101474533474304.0000 - val_mse: 197385101474533474304.0000
Epoch 402/500
389/389 [==============================] - 0s 90us/step - loss: 54396816229715247104.0000 - mse: 54396816060124758016.0000 - val_loss: 197332782313237381120.0000 - val_mse: 197332782313237381120.0000
Epoch 403/500
389/389 [==============================] - 0s 92us/step - loss: 53683157082386128896.0000 - mse: 53683158246907445248.0000 - val_loss: 198747739428975804416.0000 - val_mse: 198747739428975804416.0000
Epoch 404/500
389/389 [==============================] - 0s 92us/step - loss: 53051132224495738880.0000 - mse: 53051128176936222720.0000 - val_loss: 199362392817181655040.0000 - val_mse: 199362392817181655040.0000
Epoch 405/500
389/389 [==============================] - 0s 90us/step - loss: 54118199044836139008.0000 - mse: 54118199813646319616.0000 - val_loss: 200899580441556680704.0000 - val_mse: 200899580441556680704.0000
Epoch 406/500
389/389 [==============================] - 0s 90us/step - loss: 54998612918223691776.0000 - mse: 54998613958378651648.0000 - val_loss: 199406320505734561792.0000 - val_mse: 199406320505734561792.0000
Epoch 407/500
389/389 [==============================] - 0s 92us/step - loss: 54072229023327412224.0000 - mse: 54072231431512260608.0000 - val_loss: 200100173915512373248.0000 - val_mse: 200100173915512373248.0000
Epoch 408/500
389/389 [==============================] - 0s 90us/step - loss: 56039700602189357056.0000 - mse: 56039701936301146112.0000 - val_loss: 199378331337737895936.0000 - val_mse: 199378331337737895936.0000
Epoch 409/500
389/389 [==============================] - 0s 94us/step - loss: 53658217569586806784.0000 - mse: 53658212527096463360.0000 - val_loss: 199286394573469777920.0000 - val_mse: 199286394573469777920.0000
Epoch 410/500
389/389 [==============================] - 0s 90us/step - loss: 53455204839319371776.0000 - mse: 53455203098190413824.0000 - val_loss: 200014042572638912512.0000 - val_mse: 200014042572638912512.0000
Epoch 411/500
389/389 [==============================] - 0s 92us/step - loss: 53463943520310255616.0000 - mse: 53463946414654488576.0000 - val_loss: 198913440229328158720.0000 - val_mse: 198913440229328158720.0000
Epoch 412/500
389/389 [==============================] - 0s 90us/step - loss: 52541149618500411392.0000 - mse: 52541152693741158400.0000 - val_loss: 199117720693675917312.0000 - val_mse: 199117720693675917312.0000
Epoch 413/500
389/389 [==============================] - 0s 97us/step - loss: 54362934843915001856.0000 - mse: 54362937907849723904.0000 - val_loss: 200396514289430560768.0000 - val_mse: 200396514289430560768.0000
Epoch 414/500
389/389 [==============================] - 0s 95us/step - loss: 53487502216095571968.0000 - mse: 53487506749814472704.0000 - val_loss: 200304102536139243520.0000 - val_mse: 200304102536139243520.0000
Epoch 415/500
389/389 [==============================] - 0s 95us/step - loss: 53251815584262823936.0000 - mse: 53251811039237898240.0000 - val_loss: 201841888294839779328.0000 - val_mse: 201841888294839779328.0000
Epoch 416/500
389/389 [==============================] - 0s 94us/step - loss: 55141494392070012928.0000 - mse: 55141493295384887296.0000 - val_loss: 202281816091252490240.0000 - val_mse: 202281816091252490240.0000
Epoch 417/500
389/389 [==============================] - 0s 94us/step - loss: 55525486284028092416.0000 - mse: 55525486736269377536.0000 - val_loss: 201658718453745319936.0000 - val_mse: 201658718453745319936.0000
Epoch 418/500
389/389 [==============================] - 0s 95us/step - loss: 52046073088816332800.0000 - mse: 52046073394079203328.0000 - val_loss: 201230278354819612672.0000 - val_mse: 201230278354819612672.0000
Epoch 419/500
389/389 [==============================] - 0s 94us/step - loss: 51753911379161178112.0000 - mse: 51753915562393075712.0000 - val_loss: 203864831360273219584.0000 - val_mse: 203864831360273219584.0000
Epoch 420/500
389/389 [==============================] - 0s 94us/step - loss: 54088553463985479680.0000 - mse: 54088556980161478656.0000 - val_loss: 203459999975019118592.0000 - val_mse: 203459999975019118592.0000
Epoch 421/500
389/389 [==============================] - 0s 92us/step - loss: 53224071833479798784.0000 - mse: 53224072559892365312.0000 - val_loss: 203042818875161837568.0000 - val_mse: 203042818875161837568.0000
Epoch 422/500
389/389 [==============================] - 0s 94us/step - loss: 51684526191945433088.0000 - mse: 51684523184540876800.0000 - val_loss: 203422352696884068352.0000 - val_mse: 203422352696884068352.0000
Epoch 423/500
389/389 [==============================] - 0s 95us/step - loss: 51494655717829713920.0000 - mse: 51494655118610006016.0000 - val_loss: 205107596159008899072.0000 - val_mse: 205107596159008899072.0000
Epoch 424/500
389/389 [==============================] - 0s 93us/step - loss: 53024543274664263680.0000 - mse: 53024546383823110144.0000 - val_loss: 207241070929359405056.0000 - val_mse: 207241070929359405056.0000
Epoch 425/500
389/389 [==============================] - 0s 95us/step - loss: 54856759942817144832.0000 - mse: 54856759366209503232.0000 - val_loss: 205449658624456523776.0000 - val_mse: 205449658624456523776.0000
Epoch 426/500
389/389 [==============================] - 0s 97us/step - loss: 52702419290891558912.0000 - mse: 52702420263210319872.0000 - val_loss: 203330943698197282816.0000 - val_mse: 203330943698197282816.0000
Epoch 427/500
389/389 [==============================] - 0s 93us/step - loss: 51693138494108811264.0000 - mse: 51693138957656129536.0000 - val_loss: 204948246137818578944.0000 - val_mse: 204948246137818578944.0000
Epoch 428/500
389/389 [==============================] - 0s 92us/step - loss: 52934372196050984960.0000 - mse: 52934373236205944832.0000 - val_loss: 207225413883779874816.0000 - val_mse: 207225413883779874816.0000
Epoch 429/500
389/389 [==============================] - 0s 93us/step - loss: 52703075662588723200.0000 - mse: 52703075572140474368.0000 - val_loss: 207720053378790719488.0000 - val_mse: 207720053378790719488.0000
Epoch 430/500
389/389 [==============================] - 0s 96us/step - loss: 52135312086832128000.0000 - mse: 52135314155836014592.0000 - val_loss: 206629179514362527744.0000 - val_mse: 206629179514362527744.0000
Epoch 431/500
389/389 [==============================] - 0s 92us/step - loss: 52738182786212814848.0000 - mse: 52738180779392106496.0000 - val_loss: 205039531991203053568.0000 - val_mse: 205039531991203053568.0000
Epoch 432/500
389/389 [==============================] - 0s 92us/step - loss: 52781532323852058624.0000 - mse: 52781532323852058624.0000 - val_loss: 204778288028443475968.0000 - val_mse: 204778288028443475968.0000
Epoch 433/500
389/389 [==============================] - 0s 91us/step - loss: 53202600918073081856.0000 - mse: 53202596898778644480.0000 - val_loss: 206096857556844544000.0000 - val_mse: 206096857556844544000.0000
Epoch 434/500
389/389 [==============================] - 0s 95us/step - loss: 51545488701198082048.0000 - mse: 51545487740185346048.0000 - val_loss: 206835606225407705088.0000 - val_mse: 206835606225407705088.0000
Epoch 435/500
389/389 [==============================] - 0s 97us/step - loss: 57314853305100763136.0000 - mse: 57314853949544595456.0000 - val_loss: 207836320136358264832.0000 - val_mse: 207836320136358264832.0000
Epoch 436/500
389/389 [==============================] - 0s 94us/step - loss: 50855830496408346624.0000 - mse: 50855830066779127808.0000 - val_loss: 206547833246093148160.0000 - val_mse: 206547833246093148160.0000
Epoch 437/500
389/389 [==============================] - 0s 90us/step - loss: 52435156754112970752.0000 - mse: 52435155374777040896.0000 - val_loss: 204447871590157254656.0000 - val_mse: 204447871590157254656.0000
Epoch 438/500
389/389 [==============================] - 0s 89us/step - loss: 51708586615520018432.0000 - mse: 51708584897003126784.0000 - val_loss: 206461191729824399360.0000 - val_mse: 206461191729824399360.0000
Epoch 439/500
389/389 [==============================] - 0s 90us/step - loss: 52853222890167902208.0000 - mse: 52853220481983053824.0000 - val_loss: 208495147503721644032.0000 - val_mse: 208495147503721644032.0000
Epoch 440/500
389/389 [==============================] - 0s 95us/step - loss: 52928809729981464576.0000 - mse: 52928814105415909376.0000 - val_loss: 208387500917315862528.0000 - val_mse: 208387500917315862528.0000
Epoch 441/500
389/389 [==============================] - 0s 94us/step - loss: 50901532073142427648.0000 - mse: 50901530168076009472.0000 - val_loss: 208519811748555915264.0000 - val_mse: 208519811748555915264.0000
Epoch 442/500
389/389 [==============================] - 0s 92us/step - loss: 50304540329589587968.0000 - mse: 50304534936612241408.0000 - val_loss: 208723159827043319808.0000 - val_mse: 208723159827043319808.0000
Epoch 443/500
389/389 [==============================] - 0s 90us/step - loss: 49210449446769958912.0000 - mse: 49210450498230943744.0000 - val_loss: 208400976531825885184.0000 - val_mse: 208400976531825885184.0000
Epoch 444/500
389/389 [==============================] - 0s 92us/step - loss: 51583097911922835456.0000 - mse: 51583099833948307456.0000 - val_loss: 210771031020101697536.0000 - val_mse: 210771031020101697536.0000
Epoch 445/500
389/389 [==============================] - 0s 95us/step - loss: 53965075651268665344.0000 - mse: 53965077426315722752.0000 - val_loss: 209485851460812931072.0000 - val_mse: 209485851460812931072.0000
Epoch 446/500
389/389 [==============================] - 0s 95us/step - loss: 51833706878141087744.0000 - mse: 51833704922197524480.0000 - val_loss: 208320474688486637568.0000 - val_mse: 208320474688486637568.0000
Epoch 447/500
389/389 [==============================] - 0s 98us/step - loss: 51418869360466591744.0000 - mse: 51418872379177172992.0000 - val_loss: 207710236938977935360.0000 - val_mse: 207710236938977935360.0000
Epoch 448/500
389/389 [==============================] - 0s 95us/step - loss: 52451362023539023872.0000 - mse: 52451357778123948032.0000 - val_loss: 209661175186931580928.0000 - val_mse: 209661175186931580928.0000
Epoch 449/500
389/389 [==============================] - 0s 92us/step - loss: 52033013626738139136.0000 - mse: 52033015593987735552.0000 - val_loss: 209954612850152439808.0000 - val_mse: 209954612850152439808.0000
Epoch 450/500
389/389 [==============================] - 0s 95us/step - loss: 51814012640678977536.0000 - mse: 51814010469920800768.0000 - val_loss: 210567278321335271424.0000 - val_mse: 210567278321335271424.0000
Epoch 451/500
389/389 [==============================] - 0s 92us/step - loss: 51152996877730275328.0000 - mse: 51152997273441402880.0000 - val_loss: 212663176182294904832.0000 - val_mse: 212663176182294904832.0000
Epoch 452/500
389/389 [==============================] - 0s 95us/step - loss: 52050774091765260288.0000 - mse: 52050770507753062400.0000 - val_loss: 213742210505515204608.0000 - val_mse: 213742210505515204608.0000
Epoch 453/500
389/389 [==============================] - 0s 95us/step - loss: 49431531172376190976.0000 - mse: 49431531500251119616.0000 - val_loss: 213244914590411653120.0000 - val_mse: 213244914590411653120.0000
Epoch 454/500
389/389 [==============================] - 0s 92us/step - loss: 51027157184017637376.0000 - mse: 51027160366665695232.0000 - val_loss: 212716656427869929472.0000 - val_mse: 212716656427869929472.0000
Epoch 455/500
389/389 [==============================] - 0s 93us/step - loss: 51005681132845809664.0000 - mse: 51005680307505463296.0000 - val_loss: 212031282451765526528.0000 - val_mse: 212031282451765526528.0000
Epoch 456/500
389/389 [==============================] - 0s 93us/step - loss: 50764478276615086080.0000 - mse: 50764478242696986624.0000 - val_loss: 211731793076545388544.0000 - val_mse: 211731793076545388544.0000
Epoch 457/500

389/389 [==============================] - 0s 92us/step - loss: 52355080967289716736.0000 - mse: 52355080141949370368.0000 - val_loss: 213581206818836709376.0000 - val_mse: 213581206818836709376.0000
Epoch 458/500
389/389 [==============================] - 0s 93us/step - loss: 50745051178080903168.0000 - mse: 50745047673210929152.0000 - val_loss: 213879623070708137984.0000 - val_mse: 213879623070708137984.0000
Epoch 459/500
389/389 [==============================] - 0s 95us/step - loss: 50702975643716804608.0000 - mse: 50702975960285708288.0000 - val_loss: 213754824102909050880.0000 - val_mse: 213754824102909050880.0000
Epoch 460/500
389/389 [==============================] - 0s 95us/step - loss: 50770078058243751936.0000 - mse: 50770081353952133120.0000 - val_loss: 212934869903564865536.0000 - val_mse: 212934869903564865536.0000
Epoch 461/500
389/389 [==============================] - 0s 92us/step - loss: 51250662448066109440.0000 - mse: 51250664692313489408.0000 - val_loss: 214545716010907860992.0000 - val_mse: 214545716010907860992.0000
Epoch 462/500
389/389 [==============================] - 0s 93us/step - loss: 51830083441811513344.0000 - mse: 51830080931872374784.0000 - val_loss: 213513283388519219200.0000 - val_mse: 213513283388519219200.0000
Epoch 463/500
389/389 [==============================] - 0s 92us/step - loss: 52235331929204137984.0000 - mse: 52235330131545030656.0000 - val_loss: 213942620688933191680.0000 - val_mse: 213942620688933191680.0000
Epoch 464/500
389/389 [==============================] - 0s 95us/step - loss: 51512344717427531776.0000 - mse: 51512344061677666304.0000 - val_loss: 213618783728227581952.0000 - val_mse: 213618783728227581952.0000
Epoch 465/500
389/389 [==============================] - 0s 90us/step - loss: 50316353448600313856.0000 - mse: 50316356885634088960.0000 - val_loss: 213229820494785544192.0000 - val_mse: 213229820494785544192.0000
Epoch 466/500
389/389 [==============================] - 0s 92us/step - loss: 49101118264398512128.0000 - mse: 49101115061964898304.0000 - val_loss: 213607911757252132864.0000 - val_mse: 213607911757252132864.0000
Epoch 467/500
389/389 [==============================] - 0s 90us/step - loss: 52010029933136527360.0000 - mse: 52010027004874194944.0000 - val_loss: 212083372914643042304.0000 - val_mse: 212083372914643042304.0000
Epoch 468/500
389/389 [==============================] - 0s 97us/step - loss: 52206089238809591808.0000 - mse: 52206091918339211264.0000 - val_loss: 212269146399272075264.0000 - val_mse: 212269146399272075264.0000
Epoch 469/500
389/389 [==============================] - 0s 90us/step - loss: 49149677466200162304.0000 - mse: 49149673893493997568.0000 - val_loss: 213500247578660306944.0000 - val_mse: 213500247578660306944.0000
Epoch 470/500
389/389 [==============================] - 0s 95us/step - loss: 49722338543744671744.0000 - mse: 49722339131658338304.0000 - val_loss: 215892732104142749696.0000 - val_mse: 215892732104142749696.0000
Epoch 471/500
389/389 [==============================] - 0s 90us/step - loss: 51768058521104490496.0000 - mse: 51768055281926275072.0000 - val_loss: 216491869184257425408.0000 - val_mse: 216491869184257425408.0000
Epoch 472/500
389/389 [==============================] - 0s 95us/step - loss: 48163438504289427456.0000 - mse: 48163438351657992192.0000 - val_loss: 215882968440888098816.0000 - val_mse: 215882968440888098816.0000
Epoch 473/500
389/389 [==============================] - 0s 92us/step - loss: 51401933421752991744.0000 - mse: 51401931104016400384.0000 - val_loss: 216235375111729840128.0000 - val_mse: 216235375111729840128.0000
Epoch 474/500
389/389 [==============================] - 0s 90us/step - loss: 51257331395932225536.0000 - mse: 51257332130824323072.0000 - val_loss: 216027470657056931840.0000 - val_mse: 216027470657056931840.0000
Epoch 475/500
389/389 [==============================] - 0s 95us/step - loss: 52601191037189971968.0000 - mse: 52601194824710750208.0000 - val_loss: 217298171847231143936.0000 - val_mse: 217298171847231143936.0000
Epoch 476/500
389/389 [==============================] - 0s 92us/step - loss: 51520544801658273792.0000 - mse: 51520542020374364160.0000 - val_loss: 216057500518634749952.0000 - val_mse: 216057500518634749952.0000
Epoch 477/500
389/389 [==============================] - 0s 93us/step - loss: 51227471735362584576.0000 - mse: 51227473793060438016.0000 - val_loss: 216731896970647437312.0000 - val_mse: 216731896970647437312.0000
Epoch 478/500
389/389 [==============================] - 0s 95us/step - loss: 50273164303986343936.0000 - mse: 50273168068895047680.0000 - val_loss: 214555901886627577856.0000 - val_mse: 214555901886627577856.0000
Epoch 479/500
389/389 [==============================] - 0s 95us/step - loss: 49017708608514916352.0000 - mse: 49017706109881810944.0000 - val_loss: 218483304644485316608.0000 - val_mse: 218483304644485316608.0000
Epoch 480/500
389/389 [==============================] - 0s 95us/step - loss: 50641708605916725248.0000 - mse: 50641702376293007360.0000 - val_loss: 219172830376496201728.0000 - val_mse: 219172830376496201728.0000
Epoch 481/500
389/389 [==============================] - 0s 95us/step - loss: 51593396633149562880.0000 - mse: 51593400058877313024.0000 - val_loss: 217660746801606557696.0000 - val_mse: 217660746801606557696.0000
Epoch 482/500
389/389 [==============================] - 0s 92us/step - loss: 49741218549035532288.0000 - mse: 49741219945330507776.0000 - val_loss: 218367864719661858816.0000 - val_mse: 218367864719661858816.0000
Epoch 483/500
389/389 [==============================] - 0s 95us/step - loss: 51236163044078714880.0000 - mse: 51236168731012890624.0000 - val_loss: 218032012295887912960.0000 - val_mse: 218032012295887912960.0000
Epoch 484/500
389/389 [==============================] - 0s 92us/step - loss: 49104048423315415040.0000 - mse: 49104048558987804672.0000 - val_loss: 218527918428293955584.0000 - val_mse: 218527918428293955584.0000
Epoch 485/500
389/389 [==============================] - 0s 92us/step - loss: 49169892623441133568.0000 - mse: 49169896111352053760.0000 - val_loss: 219760567720054095872.0000 - val_mse: 219760567720054095872.0000
Epoch 486/500
389/389 [==============================] - 0s 94us/step - loss: 49116086854588088320.0000 - mse: 49116086012288696320.0000 - val_loss: 219125841647571566592.0000 - val_mse: 219125841647571566592.0000
Epoch 487/500
389/389 [==============================] - ETA: 0s - loss: 27744799338369384448.0000 - mse: 27744799338369384448.000 - 0s 92us/step - loss: 49828647637851684864.0000 - mse: 49828648711924744192.0000 - val_loss: 217657527431560429568.0000 - val_mse: 217657527431560429568.0000
Epoch 488/500
389/389 [==============================] - 0s 90us/step - loss: 51511505942686973952.0000 - mse: 51511508432840556544.0000 - val_loss: 218340807937525547008.0000 - val_mse: 218340807937525547008.0000
Epoch 489/500
389/389 [==============================] - 0s 90us/step - loss: 51100476112921681920.0000 - mse: 51100475802005798912.0000 - val_loss: 219576096057192349696.0000 - val_mse: 219576096057192349696.0000
Epoch 490/500
389/389 [==============================] - 0s 90us/step - loss: 51166962812243116032.0000 - mse: 51166965469160669184.0000 - val_loss: 219585243993935446016.0000 - val_mse: 219585243993935446016.0000
Epoch 491/500
389/389 [==============================] - 0s 92us/step - loss: 51410703912265367552.0000 - mse: 51410700808759541760.0000 - val_loss: 219744013472986300416.0000 - val_mse: 219744013472986300416.0000
Epoch 492/500
389/389 [==============================] - 0s 90us/step - loss: 51093947427690561536.0000 - mse: 51093944702936809472.0000 - val_loss: 220505667167779291136.0000 - val_mse: 220505667167779291136.0000
Epoch 493/500
389/389 [==============================] - 0s 95us/step - loss: 49302232200267956224.0000 - mse: 49302228932824662016.0000 - val_loss: 220388837460258324480.0000 - val_mse: 220388837460258324480.0000
Epoch 494/500
389/389 [==============================] - 0s 86us/step - loss: 48544023866144972800.0000 - mse: 48544023306496376832.0000 - val_loss: 220762178832492920832.0000 - val_mse: 220762178832492920832.0000

Epoch 495/500
389/389 [==============================] - 0s 90us/step - loss: 50167508048441442304.0000 - mse: 50167505001465774080.0000 - val_loss: 220877847455734956032.0000 - val_mse: 220877847455734956032.0000
Epoch 496/500
389/389 [==============================] - 0s 92us/step - loss: 49792877138443501568.0000 - mse: 49792875001603424256.0000 - val_loss: 220203732478698979328.0000 - val_mse: 220203732478698979328.0000
Epoch 497/500
389/389 [==============================] - 0s 93us/step - loss: 50449568491068571648.0000 - mse: 50449573714455429120.0000 - val_loss: 222557285496465129472.0000 - val_mse: 222557285496465129472.0000
Epoch 498/500
389/389 [==============================] - 0s 90us/step - loss: 51141165109419499520.0000 - mse: 51141162130280022016.0000 - val_loss: 221742151556097114112.0000 - val_mse: 221742151556097114112.0000
Epoch 499/500
389/389 [==============================] - 0s 95us/step - loss: 49544975842561753088.0000 - mse: 49544979110005047296.0000 - val_loss: 220682028832874561536.0000 - val_mse: 220682028832874561536.0000
Epoch 500/500
389/389 [==============================] - 0s 92us/step - loss: 47798390643682353152.0000 - mse: 47798391695143337984.0000 - val_loss: 219978974709795520512.0000 - val_mse: 219978974709795520512.0000

In [87]:
pred = model.predict(x_test)
RMSLE = np.sqrt(mean_squared_log_error(y_test, pred))
MAE = mean_absolute_error(y_test, pred)
print('rmsle는',RMSLE)
print('mae는',MAE)

ValueError: Mean Squared Logarithmic Error cannot be used when targets contain negative values.

In [ ]:
x_train = x_train.reshape(7550,5,1)
x_test = x_test.reshape(1888,5,1)

In [46]:
from keras.models import Sequential, Model 
from keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense, LSTM

model = Sequential()
model.add(LSTM(160, input_shape=(5,)))
model.add(Dense(160))
model.add(Dropout(0.2))

model.add(Dense(128))
model.add(Dense(64))
model.add(Dropout(0.2))

model.add(Dense(1, activation='relu'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_11 (Dense)             (None, 16)                96
_________________________________________________________________
dense_12 (Dense)             (None, 16)                272
_________________________________________________________________
dropout_5 (Dropout)          (None, 16)                0
_________________________________________________________________
dense_13 (Dense)             (None, 64)                1088
_________________________________________________________________
dense_14 (Dense)             (None, 64)                4160
_________________________________________________________________
dropout_6 (Dropout)          (None, 64)                0
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 65
=================================================================
Total params: 5,681
Trainable params: 5,681
Non-trainable params: 0
_________________________________________________________________

In [48]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(x_train, y_train, epochs=50, batch_size=2, validation_split=0.2)

Train on 6040 samples, validate on 1510 samples
Epoch 1/50
6040/6040 [==============================] - 9s 1ms/step - loss: 389524191217854513152.0000 - mse: 389523966780017475584.0000 - val_loss: 385864514416192389120.0000 - val_mse: 385864651345290592256.0000
Epoch 2/50
6040/6040 [==============================] - 9s 1ms/step - loss: 385136523063873503232.0000 - mse: 385136299658679681024.0000 - val_loss: 380919034811891974144.0000 - val_mse: 380918924898251833344.0000
Epoch 3/50
6040/6040 [==============================] - 9s 1ms/step - loss: 377712754277390483456.0000 - mse: 377712608254168662016.0000 - val_loss: 371906013596131655680.0000 - val_mse: 371906096143976628224.0000
Epoch 4/50
6040/6040 [==============================] - 9s 1ms/step - loss: 364756766988976455680.0000 - mse: 364756174338688811008.0000 - val_loss: 359675310217679077376.0000 - val_mse: 359675445455945203712.0000
Epoch 5/50
6040/6040 [==============================] - 9s 1ms/step - loss: 353232261487315255296.0000 - mse: 353232588792154554368.0000 - val_loss: 350555572828409757696.0000 - val_mse: 350555621026147860480.0000
Epoch 6/50
6040/6040 [==============================] - 9s 1ms/step - loss: 343882862184276754432.0000 - mse: 343882975228245049344.0000 - val_loss: 341616909560680349696.0000 - val_mse: 341616785006375469056.0000
Epoch 7/50
6040/6040 [==============================] - 9s 1ms/step - loss: 335141414338634252288.0000 - mse: 335141277245286383616.0000 - val_loss: 333422468459475697664.0000 - val_mse: 333422274378142318592.0000
Epoch 8/50
6040/6040 [==============================] - 8s 1ms/step - loss: 325003105143883169792.0000 - mse: 325002759690401087488.0000 - val_loss: 325742230776628117504.0000 - val_mse: 325742088901103714304.0000
Epoch 9/50
6040/6040 [==============================] - 8s 1ms/step - loss: 318533856657142906880.0000 - mse: 318533725853776347136.0000 - val_loss: 318922639927473668096.0000 - val_mse: 318922653902846296064.0000
Epoch 10/50
6040/6040 [==============================] - 8s 1ms/step - loss: 311842782967716315136.0000 - mse: 311842186048061833216.0000 - val_loss: 313162420392460156928.0000 - val_mse: 313162338873206898688.0000
Epoch 11/50
6040/6040 [==============================] - 9s 1ms/step - loss: 306217409992636825600.0000 - mse: 306217190113476083712.0000 - val_loss: 310159092621230211072.0000 - val_mse: 310159247162308820992.0000
Epoch 12/50
6040/6040 [==============================] - 8s 1ms/step - loss: 302969822488934023168.0000 - mse: 302969391094700179456.0000 - val_loss: 308749728997884100608.0000 - val_mse: 308749726032058122240.0000
Epoch 13/50
6040/6040 [==============================] - 9s 1ms/step - loss: 303059395554064400384.0000 - mse: 303059146427898789888.0000 - val_loss: 308084685369957679104.0000 - val_mse: 308084706215207108608.0000
Epoch 14/50
6040/6040 [==============================] - 8s 1ms/step - loss: 300958486352346152960.0000 - mse: 300958357939218808832.0000 - val_loss: 307611635819705139200.0000 - val_mse: 307611652332472762368.0000
Epoch 15/50
6040/6040 [==============================] - 8s 1ms/step - loss: 302851614135043096576.0000 - mse: 302851769738807214080.0000 - val_loss: 307159430597300846592.0000 - val_mse: 307159357229270827008.0000
Epoch 16/50
6040/6040 [==============================] - 8s 1ms/step - loss: 300333833259459018752.0000 - mse: 300333870519014129664.0000 - val_loss: 306744157335551934464.0000 - val_mse: 306744111269878431744.0000
Epoch 17/50
6040/6040 [==============================] - 9s 1ms/step - loss: 299129534652576104448.0000 - mse: 299129368724925054976.0000 - val_loss: 306331880129249345536.0000 - val_mse: 306331996719601942528.0000
Epoch 18/50
6040/6040 [==============================] - 8s 1ms/step - loss: 300236094357023293440.0000 - mse: 300236022780235087872.0000 - val_loss: 305899069575331512320.0000 - val_mse: 305899228942909308928.0000
Epoch 19/50
6040/6040 [==============================] - 9s 1ms/step - loss: 301869532489256140800.0000 - mse: 301869457254459113472.0000 - val_loss: 305504159977406595072.0000 - val_mse: 305504178813095903232.0000
Epoch 20/50
6040/6040 [==============================] - 9s 1ms/step - loss: 301424428091462320128.0000 - mse: 301424797160000454656.0000 - val_loss: 305101241599225823232.0000 - val_mse: 305101317752678776832.0000
Epoch 21/50
6040/6040 [==============================] - 9s 2ms/step - loss: 301290891797064122368.0000 - mse: 301290709517969915904.0000 - val_loss: 304733898870914351104.0000 - val_mse: 304733957723699281920.0000
Epoch 22/50
 654/6040 [==>...........................] - ETA: 7s - loss: 236283470478925365248.0000 - mse: 236283623841992802304.0000

KeyboardInterrupt: